### ISSUE TITLE
Plugin v3.87.0 crashes

### ISSUE THREAD

**Issue by dv-stephen** [hashicorp/terraform-provider-google#10291]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.0.8

### Affected Resource(s)

* google.resourceComputeInstanceTemplateRead
* beta.resourceComputeRegionInstanceGroupManagerRead

### Panic Output

```
Stack trace from the terraform-provider-google_v3.87.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *google.Config

goroutine 165 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceComputeInstanceTemplateRead(0xc000787000, 0x0, 0x0, 0x44e5790, 0xc000070400)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/resource_compute_instance_template.go:1215 +0x29d3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0005b9960, 0x359b860, 0xc000958980, 0xc000787000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0005b9960, 0x359b860, 0xc000958980, 0xc000af01c0, 0x0, 0x0, 0xc00000f130, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000dd800, 0x359b860, 0xc000958980, 0xc0009589c0, 0xc000958980, 0x40ba05, 0x2dce580)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000b50de0, 0x359b908, 0xc000958980, 0xc001041ce0, 0xc000b50de0, 0xc000a708d0, 0xc000107ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x2f8a2c0, 0xc000b50de0, 0x359b908, 0xc000a708d0, 0xc001041c80, 0x0, 0x359b908, 0xc000a708d0, 0xc000a7a000, 0x2c29)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004036c0, 0x35d9bf8, 0xc000001500, 0xc000a0ec60, 0xc000720990, 0x44a2990, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0004036c0, 0x35d9bf8, 0xc000001500, 0xc000a0ec60, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000c9330, 0xc0004036c0, 0x35d9bf8, 0xc000001500, 0xc000a0ec60)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd

Error: The terraform-provider-google_v3.87.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.


Stack trace from the terraform-provider-google-beta_v3.87.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *google.Config

goroutine 34 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta.resourceComputeRegionInstanceGroupManagerRead(0xc000205280, 0x0, 0x0, 0x4822db0, 0xc0001d7400)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/resource_compute_region_instance_group_manager.go:525 +0x15a7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00083f880, 0x3804800, 0xc000e99580, 0xc000205280, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00083f880, 0x3804800, 0xc000e99580, 0xc00037ca80, 0x0, 0x0, 0xc00000ec28, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0008fc1e0, 0x3804800, 0xc000e99580, 0xc000e995c0, 0xc000e99580, 0x40ba05, 0x2fe59e0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000f440c0, 0x38048a8, 0xc000e99580, 0xc000ebe240, 0xc000f440c0, 0xc000ea9aa0, 0xc000f51ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x31a6ba0, 0xc000f440c0, 0x38048a8, 0xc000ea9aa0, 0xc000ebe1e0, 0x0, 0x38048a8, 0xc000ea9aa0, 0xc000981500, 0x684)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c6540, 0x3845d38, 0xc000001380, 0xc000c16000, 0xc0001fa990, 0x47dfbf0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001c6540, 0x3845d38, 0xc000001380, 0xc000c16000, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00004e280, 0xc0001c6540, 0x3845d38, 0xc000001380, 0xc000c16000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd

Error: The terraform-provider-google-beta_v3.87.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by dv-stephen** [comment]
I think this should be a straight-forward fix, but please let me know if more information is needed. Thanks!

**Comment by edwardmedia** [comment]
@dv-stephen do you have the config that can be used to repro the issue?

**Comment by dv-stephen** [comment]
@edwardmedia It's a very large terraform run with a lot that I can't post here, but I updated the issue with the two [modified] resources that are most likely being affected.
