### ISSUE TITLE
Terraform google provider v4.6.0 crashing on destroy

### ISSUE THREAD

**Issue by nyanchor** [hashicorp/terraform-provider-google#10980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```bash
terraform 1.1.4
```

### Affected Resource(s)

* google_storage_bucket
* google_compute_instance_from_template
* google_pubsub_topic

### Terraform Configuration Files

```tf
# Copy-paste your Terraform configurations here.
#
# For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
# For security, you can also encrypt the files using our GPG public key:
#    https://www.hashicorp.com/security
#
# If reproducing the bug involves modifying the config file (e.g., apply a config,
# change a value, apply the config again, see the bug), then please include both:
# * the version of the config before the change, and
# * the version of the config after the change.
```

### Panic Output

```bash
module.instance_template.google_compute_instance_template.tpl (deposed object a56650d4): Refreshing state... [id=projects/XXXX/global/instanceTemplates/default-instance-template-YYY]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed
│ to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState
│ call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_storage_bucket_object.archive,
│   on zzzz.tf line 40, in resource "google_storage_bucket_object" "archive":
│   40: resource "google_storage_bucket_object" "archive" {
│
│ The plugin encountered an error, and failed
│ to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState
│ call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_pubsub_topic.topic,
│   on backup.tf line 136, in resource "google_pubsub_topic" "topic":
│  136: resource "google_pubsub_topic" "topic" {
│
│ The plugin encountered an error, and failed
│ to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState
│ call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_storage_bucket.bucket,
│   on main.tf line 34, in resource "google_storage_bucket" "bucket":
│   34: resource "google_storage_bucket" "bucket" {
│
│ The plugin encountered an error, and failed
│ to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState
│ call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_service_account.vm_service_account,
│   on main.tf line 107, in resource "google_service_account" "vm_service_account":
│  107: resource "google_service_account" "vm_service_account" {
│
│ The plugin encountered an error, and failed
│ to respond to the
│ plugin.(*GRPCProvider).ReadResource call.
│ The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_compute_instance_from_template.vm,
│   on main.tf line 171, in resource "google_compute_instance_from_template" "vm":
│  171: resource "google_compute_instance_from_template" "vm" {
│
│ The plugin encountered an error, and failed
│ to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState
│ call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.instance_template.google_compute_instance_template.tpl,
│   on .terraform/modules/instance_template/modules/instance_template/main.tf line 58, in resource "google_compute_instance_template" "tpl":
│   58: resource "google_compute_instance_template" "tpl" {
│
│ The plugin encountered an error, and failed
│ to respond to the
│ plugin.(*GRPCProvider).UpgradeResourceState
│ call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.instance_template.google_compute_instance_template.tpl,
│   on .terraform/modules/instance_template/modules/instance_template/main.tf line 58, in resource "google_compute_instance_template" "tpl":
│   58: resource "google_compute_instance_template" "tpl" {
│
│ The plugin encountered an error, and failed
│ to respond to the
│ plugin.(*GRPCProvider).ReadResource call.
│ The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-google_v4.6.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *google.Config

goroutine 104 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceGoogleServiceAccountRead(0xc00028a880, 0x0, 0x0, 0x42b6b70, 0x4287fc0)
        github.com/hashicorp/terraform-provider-google/google/resource_google_service_account.go:122 +0xc9f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a34a80, 0x33cb1a0, 0xc00043b1c0, 0xc00028a880, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a34a80, 0x33cb1a0, 0xc00043b1c0, 0xc0006ee150, 0x0, 0x0, 0xc0008263f0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c9c0, 0x33cb1a0, 0xc00043b1c0, 0xc00043b200, 0xc00043b1c0, 0x40ba05, 0x2c78540)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000b73960, 0x33cb248, 0xc00043b1c0, 0xc000d82f00, 0xc000b73960, 0xc000b0dda0, 0xc0005bcba0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x2dd6e80, 0xc000b73960, 0x33cb248, 0xc000b0dda0, 0xc000d82ea0, 0x0, 0x33cb248, 0xc000b0dda0, 0xc0011f4900, 0x213)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00041f880, 0x34017d8, 0xc000643200, 0xc0011ecfc0, 0xc000a5f650, 0x4273690, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1297 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00041f880, 0x34017d8, 0xc000643200, 0xc0011ecfc0, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000be2a0, 0xc00041f880, 0x34017d8, 0xc000643200, 0xc0011ecfc0)
        google.golang.org/grpc@v1.40.0/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd

Error: The terraform-provider-google_v4.6.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by c2thorn** [comment]
Can you share the full config that reproduces this issue, along with a sanitized debug log? Considering where the crash failure is, it seems extremely abnormal and not something I know how to reproduce.

Does this happen consistently? Can you reproduce it with just the `google_service_account` resource?

**Comment by nyanchor** [comment]
@c2thorn I fixed the issue, there seemed to be an issue with my terraform configs, it seems I had some dependencies in the way the infrastructure was being provisioned. Once I fixed that, this issue went away. Thanks!
