### ISSUE TITLE
panic: Version name doesn not fit the format `projects/{{project}}/secrets/{{secret}}/versions{{version}}`

### ISSUE THREAD

**Issue by dex4er** [hashicorp/terraform-provider-google#11140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.10.0
+ provider registry.terraform.io/hashicorp/google-beta v4.10.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* google_secret_manager_secret_version

### Terraform Configuration Files

```tf
resource "google_secret_manager_secret_version" "secret" {
  secret = google_secret_manager_secret.secret.id

  secret_data = random_id.secret.b64_std
}
```

### Panic Output

```
$ terraform import module.app.google_secret_manager_secret_version.secret app-secret/1

module.app.google_secret_manager_secret_version.secret: Importing from ID "app-secret/1"...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ImportResourceState call. The plugin
│ logs may contain more details.
╵


Stack trace from the terraform-provider-google_v4.10.0_x5 plugin:

panic: Version name doesn not fit the format `projects/{{project}}/secrets/{{secret}}/versions{{version}}`

goroutine 74 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceSecretManagerSecretVersionImport(0xc000e3b280, 0x2cbfb20, 0xc000219800, 0x24, 0xc000a14550, 0x1, 0x30, 0x7f5e9223d5b8)
        github.com/hashicorp/terraform-provider-google/google/resource_secret_manager_secret_version.go:269 +0x338
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc000090180, 0x3174ef0, 0xc000ba8980, 0xc000693a10, 0xc000dd7380, 0x36, 0xc000d8bae0, 0x9, 0xc000000001, 0x2cfabe7, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/provider.go:384 +0x328
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc00000df50, 0x3174ef0, 0xc000ba8980, 0xc000288aa0, 0x2cfabe7, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1043 +0xe5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ImportResourceState(0xc000a1c380, 0x3174f98, 0xc000ba8980, 0xc000e23090, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:628 +0x2f8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ImportResourceState_Handler(0x2c52800, 0xc000a1c380, 0x3174f98, 0xc000d896b0, 0xc000a2dda0, 0x0, 0x3174f98, 0xc000d896b0, 0xc000e3c9c0, 0x5e)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:398 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000435a40, 0x31a9c98, 0xc000103080, 0xc00061ea20, 0xc0008fcc30, 0x3fb2798, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1297 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000435a40, 0x31a9c98, 0xc000103080, 0xc00061ea20, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005ba350, 0xc000435a40, 0x31a9c98, 0xc000103080, 0xc00061ea20)
        google.golang.org/grpc@v1.40.0/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd

Error: The terraform-provider-google_v4.10.0_x5 plugin crashed!
```

It is suspicous that error shows "projects/{{project}}/secrets/{{secret}}/versions{{version}}" string rather than "projects/{{project}}/secrets/{{secret}}/versions/{{version}}" (missing slash after "versions"?)

**Comment by ScottSuarez** [comment]
You need to import with the fully quantified resource location as mentioned... `projects/{{project}}/secrets/{{secret}}/versions/{{version}}`

The missing slash is simply a faulty print statement (i'm correcting now)
