### ISSUE TITLE
terraform-provider-google_v3.90.1_x5 plugin crashes

### ISSUE THREAD

**Issue by mro-amboss** [hashicorp/terraform-provider-google#12001]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.2.4

### Affected Resource(s)

* provider registry.terraform.io/hashicorp/google v3.90.1

### Terraform Configuration Files

```provider "google" {
  project = "XXXXXX"
  region  = "europe-west1"
}
```

### Debug Output

```
2022-07-01T12:53:32.238+0200 [DEBUG] [aws-sdk-go] {}

Stack trace from the terraform-provider-google_v3.90.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb41365]

goroutine 16 [running]:
golang.org/x/oauth2/authhandler.authHandlerSource.Token(0x35aae20, 0xc000f59dc0, 0xc000ec87e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/golang.org/x/oauth2@v0.0.0-20210819190943-2bc19b11175f/authhandler/authhandler.go:48 +0x65
golang.org/x/oauth2.(*reuseTokenSource).Token(0xc000e9af80, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/golang.org/x/oauth2@v0.0.0-20210819190943-2bc19b11175f/oauth2.go:304 +0xaf
golang.org/x/oauth2.(*Transport).RoundTrip(0xc000e9afa0, 0xc00022c200, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/golang.org/x/oauth2@v0.0.0-20210819190943-2bc19b11175f/transport.go:45 +0x9e
net/http.send(0xc00022c200, 0x357c6a0, 0xc000e9afa0, 0x0, 0x0, 0x0, 0xc00021fe18, 0x418377, 0x1, 0x0)
        /opt/goenv/versions/1.16.2/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc0010c4750, 0xc00022c200, 0x0, 0x0, 0x0, 0xc00021fe18, 0x0, 0x1, 0xc000e9a000)
        /opt/goenv/versions/1.16.2/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc0010c4750, 0xc00022c200, 0x0, 0x0, 0x0)
        /opt/goenv/versions/1.16.2/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        /opt/goenv/versions/1.16.2/src/net/http/client.go:585
github.com/hashicorp/terraform-provider-google/google.sendRequestWithTimeout.func1(0xc0016b0400, 0xc000202f00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/transport.go:83 +0x25b
github.com/hashicorp/terraform-provider-google/google.retryTimeDuration.func1(0x2)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/retry_utils.go:21 +0x32
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/resource/wait.go:27 +0x5b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc0016b0240, 0xc0016c40e0, 0xc00004e1e0, 0xc000226100, 0xc0016b20b0, 0xc0016b20a8)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/resource/state.go:110 +0x2e9
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/resource/state.go:83 +0x1c6

Error: The terraform-provider-google_v3.90.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. `terraform plan`

**Comment by edwardmedia** [comment]
@mro-amboss can you share the terraform config that can be used to repro the issue?

**Comment by mro-amboss** [comment]
i am afraid this is not possible.
