### ISSUE TITLE
Error: The terraform-provider-google_v4.10.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by anoojnairp** [hashicorp/terraform-provider-google#13050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v1.3.4
on windows_386
+ provider registry.terraform.io/hashicorp/google v4.10.0
+ provider registry.terraform.io/hashicorp/google-beta v4.43.0
+ provider registry.terraform.io/innovationnorway/git v0.1.3

### Affected Resource(s)

google_bigquery_dataset.default
google_project.project

### Terraform Configuration Files

terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.10.0"
    }
    git = {
      source  = "innovationnorway/git"
      version = "0.1.3"
    }
  }

  backend "gcs" {
    bucket = "project-infra-state"
    prefix = "terraform/projectname"
  }
}

module "common" {
  source = "../terraform-common"
}

provider "google" {
  project = module.common.project
  region  = module.common.region
}

provider "google-beta" {
  project = module.common.project
  region  = module.common.region
}

data "google_project" "project" {
}

# Dataset
resource "google_bigquery_dataset" "default" {
  dataset_id = "dataset_projectname"
  location   = module.common.region
}
```

### Debug Output

<!---
Please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

To obtain the debug output, run `terraform apply` with the environment variable `TF_LOG=DEBUG`. See the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html) for more information.
--->

### Panic Output

panic: Error reading level state: strconv.ParseInt: parsing "1663736759621": value out of range

### Expected Behavior

1 to add 0 to destroy

### Actual Behavior

<!--- What actually happened? --->

 Error: Plugin did not respond
│
│   with data.google_project.project,
│   on main.tf line 34, in data "google_project" "project":
│   34: data "google_project" "project" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more  
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_bigquery_dataset.default,
│   on main.tf line 38, in resource "google_bigquery_dataset" "default":
│   38: resource "google_bigquery_dataset" "default" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more    
│ details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-google_v4.10.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "1663736759621": value out of range

goroutine 43 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x15264910, 0x14ba1918, 0x1, 0x1, 0x14fcc808, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:553 +0x2ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x15264910, 0x15264910)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:351 +0x288
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x14d45960, 0x29eb24c, 0x14ba0bc0, 0x22093a0, 0x15042e60, 0x29eb24c, 0x14ba0bc0, 0x22093a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:263 +0x191
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14c992d0, 0x29eadac, 0x150424a0, 0x15042520, 0x259947e, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:550 +0x1ea
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14a0e200, 0x29eae0c, 0x150424a0, 0x14fd6090, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x288
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x2551640, 0x14a0e200, 0x29eae0c, 0x15080090, 0x14fd6060, 0x0, 0x29eae0c, 0x15080090, 0x148b3200, 0x413)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x199
google.golang.org/grpc.(*Server).processUnaryRPC(0x14892120, 0x29fdbc8, 0x14b91400, 0x1556e0a0, 0x14988f90, 0x36ad7e8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1297 +0x4ea
google.golang.org/grpc.(*Server).handleStream(0x14892120, 0x29fdbc8, 0x14b91400, 0x1556e0a0, 0x0)
        google.golang.org/grpc@v1.40.0/server.go:1626 +0xa71
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14a08160, 0x14892120, 0x29fdbc8, 0x14b91400, 0x1556e0a0)
        google.golang.org/grpc@v1.40.0/server.go:941 +0x92
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.40.0/server.go:939 +0x1b0

Error: The terraform-provider-google_v4.10.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

<!--- Please list the steps required to reproduce the issue. --->

1. `terraform apply`

### Important Factoids

<!--- Are there anything atypical about your accounts that we should know? For example: authenticating as a user instead of a service account? --->

### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:
--->

* #0000

<!---
Note Google Cloud customers who are working with a dedicated Technical Account Manager / Customer Engineer: to expedite the investigation and resolution of this issue, please refer to these instructions: https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team
--->

**Comment by c2thorn** [comment]
Hi folks, apologies for your experience with this crash. 
It seems somewhere we are expecting a value to be an Integer, but didn't expect the value to go above the maximum for the type. 

I cannot determine which field is returning the out of range value from the crash log. Does anyone have a sanitized [DEBUG log](https://developer.hashicorp.com/terraform/internals/debugging) of this scenario that would show me the API request/response body before this?

**Comment by anoojnairp** [comment]
Hi Cameron, thanks for responding. My other colleagues were able to apply terraform from the same folder, and so I reinstalled my terraform by using chocolatey and it fixed the issue.  Thanks again.
