### ISSUE TITLE
 SIGSEGV in google_cloudfunctions_function with parameter https_trigger_security_level

### ISSUE THREAD

**Issue by Kaawin1** [hashicorp/terraform-provider-google#13156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
Terraform v1.2.4
on linux_amd64
```

terragrunt `v0.38.9`

### Affected Resource(s)

* `google_cloudfunctions_function` when settings the parameter `https_trigger_security_level`

### Panic Output

```
Stack trace from the terraform-provider-google_v4.44.1_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e6ee05]

goroutine 77 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceCloudFunctionsUpdate(0xc000752380, {0x2d22880?, 0xc0002af000})
	github.com/hashicorp/terraform-provider-google/google/resource_cloudfunctions_function.go:827 +0x1845
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x329c660?, {0x329c660?, 0xc0018f6450?}, 0xd?, {0x2d22880?, 0xc0002af000?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0009c0ee0, {0x329c660, 0xc0018f6450}, 0xc0019cc820, 0xc000752200, {0x2d22880, 0xc0002af000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00062cd98, {0x329c660?, 0xc0018f6390?}, 0xc001743cc0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0005340a0, {0x329c660?, 0xc0018bdc20?}, 0xc0003e47e0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x2cb4f00?, 0xc0005340a0}, {0x329c660, 0xc0018bdc20}, 0xc0003e4770, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x32a1af8, 0xc0002cd1e0}, 0xc00188a480, 0xc0002c5020, 0x440ef40, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x32a1af8, 0xc0002cd1e0}, 0xc00188a480, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-google_v4.44.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Actual Behavior

Terraform crash

### Steps to Reproduce

1. `terragrunt apply`

Terraform crashes only when I define the parameter `https_trigger_security_level`

**Comment by ScottSuarez** [comment]
I'm wondering if this is an issue specific to terragrunt, we should have a test guarding this scenario so its a bit strange.
