### ISSUE TITLE
[Broken] Issue with magic-module main

### ISSUE THREAD

**Issue by shubhamkr619** [hashicorp/terraform-provider-google#13846]
If you have a support request or question please submit them to one of these resources:
Magic-module main is broken. Currently, getting the issue with ruby compilation. 

```ruby
Bundle complete! 7 Gemfile dependencies, 35 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
bundler: failed to load command: compiler (compiler)
Traceback (most recent call last):
	18: from /usr/local/bin/bundle:23:in `<main>'
	17: from /usr/local/bin/bundle:23:in `load'
	16: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
	15: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	14: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
	13: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
	12: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	11: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
	10: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	 9: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	 8: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	 7: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
	 6: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
	 5: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
	 4: from /var/lib/gems/2.7.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
	 3: from compiler:30:in `<top (required)>'
	 2: from compiler:30:in `require'
	 1: from /home/kodrama/mm_2/mmv1/provider/terraform.rb:20:in `<top (required)>'
/home/kodrama/mm_2/mmv1/provider/terraform.rb:20:in `require': /home/kodrama/mm_2/mmv1/provider/terraform/examples.rb:171: syntax error, unexpected ',' (SyntaxError)
                         vars:,
                              ^
/home/kodrama/mm_2/mmv1/provider/terraform/examples.rb:172: syntax error, unexpected ',', expecting `end'
...|k, v| [k, docs_defaults[v]] },
...                              ^
/home/kodrama/mm_2/mmv1/provider/terraform/examples.rb:176: syntax error, unexpected ')', expecting `end'
                     ))
                     ^
/home/kodrama/mm_2/mmv1/provider/terraform/examples.rb:227: syntax error, unexpected ','
...          primary_resource_id:,
...                              ^
/home/kodrama/mm_2/mmv1/provider/terraform/examples.rb:231: syntax error, unexpected ')', expecting `end'
                     ))
                     ^
/home/kodrama/mm_2/mmv1/provider/terraform/examples.rb:250: syntax error, unexpected '}'
                       },
                       ^
/home/kodrama/mm_2/mmv1/provider/terraform/examples.rb:252: syntax error, unexpected ')', expecting `end'
                     ))
                     ^
make[1]: *** [GNUmakefile:64: mmv1] Error 1
make[1]: Leaving directory '/home/kodrama/mm_2'
make: *** [GNUmakefile:60: provider] Error 2
```

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html) 
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
* [Google Cloud Platform Slack](https://gcp-slack.appspot.com/)

**Comment by rileykarson** [comment]
Can you run `ruby --version` and `which ruby` from MM's top-level directory? We've seen this happen when folks are using a system version of ruby rather than `rbenv`'s version.

**Comment by ggtisc** [comment]
Hi @shubhamkr619 

I see this is was opened for so long waiting for an answer. I'm going to close it but if you are still having the same issue please open a new one with all the required information.
