### ISSUE TITLE
Crash after adding `share_settings` in google_compute_reservation

### ISSUE THREAD

**Issue by edwardmedia** [hashicorp/terraform-provider-google#14145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Affected Resource(s)

* google_compute_reservation

### Terraform Configuration Files

```tf
resource "google_compute_reservation" "t4_reservation_13_us_central1_a" {
  name = "issue14137"
  zone = "us-west1-a"

  specific_reservation {
    count = 1
    instance_properties {
      min_cpu_platform = "Intel Skylake"
      machine_type     = "custom-44-286720"
      guest_accelerators {
        accelerator_type  = "nvidia-tesla-t4"
        accelerator_count = 4
      }
    }
  }
/*
  share_settings {
    share_type = "SPECIFIC_PROJECTS"
  }*/
}
```

### Steps to Reproduce

1. `terraform apply`
2. uncomment the block of `share_settings`
3. `terraform apply`

### Important Factoids

google_compute_reservation.t4_reservation_13_us_central1_a: Modifying... [id=projects/sunedward-tf-host/zones/us-west1-a/reservations/issue14137]
╷
│ Error: Plugin did not respond
│ 
│   with google_compute_reservation.t4_reservation_13_us_central1_a,
│   on main.tf line 1, in resource "google_compute_reservation" "t4_reservation_13_us_central1_a":
│    1: resource "google_compute_reservation" "t4_reservation_13_us_central1_a" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-google_v4.59.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 103 [running]:
github.com/hashicorp/terraform-provider-google/google.resourceComputeReservationUpdateEncoder(0x1039e0200?, {0x103e2ebe0?, 0x14000d4d000}, 0xd?)
        github.com/hashicorp/terraform-provider-google/google/resource_compute_reservation.go:1069 +0x1090
github.com/hashicorp/terraform-provider-google/google.resourceComputeReservationUpdate(0x14001845380, {0x103e2ebe0?, 0x14000d4d000?})
        github.com/hashicorp/terraform-provider-google/google/resource_compute_reservation.go:428 +0x2fc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x103e71338?, {0x103e71338?, 0x140010261e0?}, 0xd?, {0x103e2ebe0?, 0x14000d4d000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:729 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400041e540, {0x103e71338, 0x140010261e0}, 0x14000a69ad0, 0x14001845200, {0x103e2ebe0, 0x14000d4d000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:847 +0x680
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000dba8, {0x103e71338?, 0x140010260c0?}, 0x14000dd1900)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xb94
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x14000b252f0, 0x14000b25350, {0x1400106cc10, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000fc8500, {0x103e71338?, 0x14000fdb320?}, 0x1400182d260)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x103dbb380?, 0x14000fc8500}, {0x103e71338, 0x14000fdb320}, 0x1400182d1f0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000d97e00, {0x103e77080, 0x14000668680}, 0x14000dfc5a0, 0x140010bbb90, 0x10505f300, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x14000d97e00, {0x103e77080, 0x14000668680}, 0x14000dfc5a0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x298

Error: The terraform-provider-google_v4.59.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by zli82016** [comment]
I tested locally and got the error 

Invalid value for field 'resource.shareSettings.projectMap': ''. Have to share with at least 1 project.
