### ISSUE TITLE
Plugin did not respond with resource google_dataproc_cluster

### ISSUE THREAD

**Issue by asarto1** [hashicorp/terraform-provider-google#14553]
I created a project with a Dataproc Cluster. Everything worked fine since not too long ago.  Then suddenly without any change to the code or command to invoke terraform, we started having this issue. We tried upgrading and downgrading the google provider version but nothing seems to work.

_Plugin did not respond. The plugin encountered an error, and failed to respond to the plugin. (*GRPCProvider).ApplyResourceChange call._

This error occurred while trying to provision a GKE based Dataproc cluster. We tried upgrading and downgrading our plugin (we went from 4.48 to 4.64), deleting the tf state but nothing worked.

### Terraform Version

I tried on Terraform 1.4.6 and 1.3.7 and  terraform-provider-google_v4.56.0/4.64.0/4.48.0

### Affected Resource(s)

resource "google_dataproc_cluster"

### Debug Output

Stack trace from the terraform-provider-google_v4.56.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x2321220]

goroutine 32 [running]:
github.com/hashicorp/terraform-provider-google/google.flattenGceClusterConfig(0x2aa5aa0?, 0x0)
        github.com/hashicorp/terraform-provider-google/google/resource_dataproc_cluster.go:2425 +0x40
github.com/hashicorp/terraform-provider-google/google.flattenClusterConfig(0xc001233b80?, 0xc000fee680)
        github.com/hashicorp/terraform-provider-google/google/resource_dataproc_cluster.go:2237 +0x1de
github.com/hashicorp/terraform-provider-google/google.resourceDataprocClusterRead(0x2f83235?, {0x2edd1e0?, 0xc00182d800})
        github.com/hashicorp/terraform-provider-google/google/resource_dataproc_cluster.go:2091 +0x465
github.com/hashicorp/terraform-provider-google/google.resourceDataprocClusterCreate(0x0?, {0x2edd1e0?, 0xc00182d800})
        github.com/hashicorp/terraform-provider-google/google/resource_dataproc_cluster.go:1355 +0x5f0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x34afd18?, {0x34afd18?, 0xc00195eae0?}, 0xd?, {0x2edd1e0?, 0xc00182d800?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000d60a80, {0x34afd18, 0xc00195eae0}, 0xc00101ec30, 0xc001232780, {0x2edd1e0, 0xc00182d800})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000daa828, {0x34afd18?, 0xc00195e9c0?}, 0xc0019662d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0005683c0, {0x34afd18?, 0xc00195e1b0?}, 0xc0005d6070)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x2e6ac20?, 0xc0005683c0}, {0x34afd18, 0xc00195e1b0}, 0xc0005d6000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x34b5720, 0xc00015e1a0}, 0xc001974000, 0xc000da4a50, 0x46c13c0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x34b5720, 0xc00015e1a0}, 0xc001974000, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-google_v4.56.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

<img width="550" alt="Immagine 2023-05-10 095322" src="https://github.com/hashicorp/terraform-provider-google/assets/133093676/a6d4b3b8-089c-4d81-979a-298f042ba269">

**Comment by asarto1** [comment]
This is the resource that I use. I see on issue #14457  that the problem might be located in the 'cluster.Config != nil' condition written in the terraform core code. We already tried to not specify the cluster_config field but it was to no avail
`

    resource "google_dataproc_cluster" "dataproc_cluster" {
      name   = var.dataproc_cluster_name
      region = var.region

    virtual_cluster_config {
      staging_bucket = module.service_connections.staging_bucket_name

    kubernetes_cluster_config {
      kubernetes_namespace = var.dataproc_cluster_name

      kubernetes_software_config {
        component_version = {
          "SPARK" : "3.1-dataproc-11"
        }
      }

      gke_cluster_config {
        gke_cluster_target = google_container_cluster.cluster_gke.id

        node_pool_target {
          node_pool = var.dataproc_nodepool_name
          roles     = ["DEFAULT", "CONTROLLER", "SPARK_DRIVER", "SPARK_EXECUTOR"]

          node_pool_config {
            autoscaling {
              min_node_count = var.autoscaling_min_node_count
              max_node_count = var.autoscaling_max_node_count
            }

            config {
              machine_type = var.machine_type
              preemptible  = true
              #local_ssd_count   = 1
            }

            locations = [var.zone]
          }
        }
      }
    }
    }
    }
`

**Comment by asarto1** [comment]
Hello
is it correct to say that the error is in resource_dataproc_cluster.go at line 2091? Since I am trying to create a GKE Cluster that GCE condition should never occur and go directly into the else.
<img width="364" alt="Immagine 2023-05-11 094140" src="https://github.com/hashicorp/terraform-provider-google/assets/133093676/3534d673-a773-41fb-9fee-23c2e7a3f306">
