### ISSUE TITLE
google_bigquery_table: Terraform Provider Plugin Crashed terraform-provider-google_v4.65.2_x5 (and other versions)

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-provider-google#14659]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

v1.4.2

### Affected Resource(s)

* google_bigquery_table

### Terraform Configuration Files

Its hard to share the configuration here, as these are internal modules we use. What i can say is the table resource exist within the state file and in GCP. I tried to revert back to an older version of the provider 4.41 and that did not work.

### Panic Output

4.41
```
Stack trace from the terraform-provider-google_v4.41.0_x5 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 217 [running]:
github.com/hashicorp/terraform-provider-google/google.bigQueryTablecheckNameExists({0xc000e85000?, 0x33, 0xc001233788?})
	github.com/hashicorp/terraform-provider-google/google/resource_bigquery_table.go:38 +0x105
github.com/hashicorp/terraform-provider-google/google.resourceBigQueryTableSchemaIsChangeable({0x2646ee0?, 0xc000d36f18?}, {0x2646ee0?, 0xc000d36f30?})
	github.com/hashicorp/terraform-provider-google/google/resource_bigquery_table.go:224 +0x3cc
github.com/hashicorp/terraform-provider-google/google.resourceBigQueryTableSchemaCustomizeDiffFunc({0x3196258, 0xc000bf3740})
	github.com/hashicorp/terraform-provider-google/google/resource_bigquery_table.go:327 +0x1db
github.com/hashicorp/terraform-provider-google/google.resourceBigQueryTableSchemaCustomizeDiff({0xc000e5ba70?, 0xc000ea7050?}, 0xc000e5baa0?, {0xc000bf3740?, 0x5f7265706c65682e?})
	github.com/hashicorp/terraform-provider-google/google/resource_bigquery_table.go:342 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff.All.func1({0x3193ec0, 0xc0010ea870}, 0x2c7794f?, {0x2c43560, 0xc0002c7000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/customdiff/compose.go:51 +0xb3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00085bf20, {0x3193ec0, 0xc0010ea870}, 0xc000edd380, 0xc000ea7440, 0xc00011e320, {0x2c43560, 0xc0002c7000}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/schema.go:677 +0x4b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x31946d8?, {0x3193ec0?, 0xc0010ea870?}, 0xc000edd380, 0x2837300?, {0x2c43560?, 0xc0002c7000?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:890 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0008ac1c8, {0x3193ec0?, 0xc0010ea7b0?}, 0xc0011640a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:741 +0x98c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc0005241e0, {0x3193ec0?, 0xc0010ea210?}, 0xc000318070)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:780 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x2bd7c40?, 0xc0005241e0}, {0x3193ec0, 0xc0010ea210}, 0xc000318000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x31991a8, 0xc00077e4e0}, 0xc000c7a000, 0xc0006ae840, 0x42b8308, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x31991a8, 0xc00077e4e0}, 0xc000c7a000, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a
Error: The terraform-provider-google_v4.41.0_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
2023-05-19T11:53:19.795Z [DEBUG] provider: plugin exited
```

4.65.2

```
Stack trace from the terraform-provider-google_v4.65.2_x5 plugin:
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 358 [running]:
github.com/hashicorp/terraform-provider-google/google.bigQueryTablecheckNameExists({0xc000293800?, 0x33, 0xc0013b7c68?})
	github.com/hashicorp/terraform-provider-google/google/resource_bigquery_table.go:42 +0x105
github.com/hashicorp/terraform-provider-google/google.resourceBigQueryTableSchemaIsChangeable({0x2ad9340?, 0xc001a77bd8?}, {0x2ad9340?, 0xc001a77bf0?})
	github.com/hashicorp/terraform-provider-google/google/resource_bigquery_table.go:245 +0x3d6
github.com/hashicorp/terraform-provider-google/google.resourceBigQueryTableSchemaCustomizeDiffFunc({0x37c6860, 0xc001a09740})
	github.com/hashicorp/terraform-provider-google/google/resource_bigquery_table.go:348 +0x1db
github.com/hashicorp/terraform-provider-google/google.resourceBigQueryTableSchemaCustomizeDiff({0x0?, 0x0?}, 0x0?, {0x0?, 0x0?})
	github.com/hashicorp/terraform-provider-google/google/resource_bigquery_table.go:363 +0x25
github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff.All.func1({0x37c3218, 0xc0007fa6f0}, 0x31c1c16?, {0x3188700, 0xc00148db00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/customdiff/compose.go:50 +0xb1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc0011ad6b0, {0x37c3218, 0xc0007fa6f0}, 0xc000afad00, 0xc0005fb7d0, 0xc000f65920, {0x3188700, 0xc00148db00}, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/schema.go:699 +0x4d4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x37c3a68?, {0x37c3218?, 0xc0007fa6f0?}, 0xc000afad00, 0x2d01a20?, {0x3188700?, 0xc00148db00?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:890 +0x6c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0012f9398, {0x37c3218?, 0xc0007fa540?}, 0xc000f44d70)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:741 +0x9c9
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.PlanResourceChange({0xc001289f80, 0xc0012be000, {0xc001875f80, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_PlanResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc0014bb4a0, {0x37c3218?, 0xc000871590?}, 0xc00268c070)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:783 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x310eb20?, 0xc0014bb4a0}, {0x37c3218, 0xc000871590}, 0xc00268c000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0018343c0, {0x37cb1e0, 0xc001a021a0}, 0xc002964000, 0xc0019d5740, 0x4b35ba8, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0018343c0, {0x37cb1e0, 0xc001a021a0}, 0xc002964000, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x28a
Error: The terraform-provider-google_v4.65.2_x5 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
2023-05-19T11:57:37.711Z [DEBUG] provider: plugin exited
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

b/285180436

**Comment by edwardmedia** [comment]
@drandell I see where the problem is. But can you detail the steps how to get to the state?

**Comment by drandell** [comment]
@edwardmedia not entirely sure to be honest. I've checked with the engineering team and looking at there pipelines in gitlab, the objects were created 3 weeks ago fine using provider version 4.41. 
Then no updates happened until 4 days ago when they added some additional resources (data catalog tags in this case) and there the pipeline fails with version 4.41. (They have stuck the version at that). 
My suggestion to the team was to upgrade to the latest version and that did not help. 

What i have done since is remove all the tables and add that back in one by one, and it seems a table called "customer_billing_account" is the source of the error. If i omit that the plan works. Happy to share the plan output for that working pipeline privately if the destruction of the table might provide any further clues for you?

**Comment by drandell** [comment]
I probably wouldn't feel comfortable doing that publically @edwardmedia maybe I can share it with my TAM who can forward it onto you?

**Comment by drandell** [comment]
I've sent the schema to my TAM and she will hopefully get it to you @edwardmedia :)

**Comment by drandell** [comment]
I've been on leave, but i have sent a chaser :)

**Comment by slevenick** [comment]
To speed this up can you send the schema directly to me, and I can forward it as appropriate? My email is my username @google.com

**Comment by drandell** [comment]
> slevenick

I've just emailed it across as-well, my TAM did say she sent this this afternoon (BST) to Edward earlier

**Comment by edwardmedia** [comment]
@drandell with your config, I can repro the issue now. The crash occurs when `tf destroy` is issued in my testing

**Comment by edwardmedia** [comment]
@drandell in your config, I see null in the columns. Is this on purpose?

```
 {
  "name": "FIRSTBILLED_DATE",
  "type": "TIMESTAMP",
  "mode": "NULLABLE",
  "description": "First bill date"
 },
 null,
 {
  "name": "GFR_VARIANT_NUMBER",
  "type": "NUMERIC",
  "mode": "NULLABLE",
  "description": "Variant for GFR code"
 },
```

**Comment by drandell** [comment]
Let me ask the team, would those just get ignored in the terraform JSON parse commands regardless?

**Comment by edwardmedia** [comment]
b/285180436

**Comment by c2thorn** [comment]
closed with https://github.com/GoogleCloudPlatform/magic-modules/pull/8460

This will release with v5.0.0. Check https://github.com/hashicorp/terraform-provider-google/issues/15582 for more details on the major release.
