### ISSUE TITLE
Exception is being thrown  when adding CORS block is being added in google_storage_bucket 

### ISSUE THREAD

**Issue by kanhaPrayas** [hashicorp/terraform-provider-google#15280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
3.209.21

### Affected Resource(s)

* google_storage_bucket

### Terraform Configuration Files

```tf
resource "google_storage_bucket" "default" {
 project           = var.project
 name            = var.name
 location          = var.bucket_location
 storage_class        = "STANDARD"
 uniform_bucket_level_access = true
 force_destroy        = true

 cors {
  origin     = var.origin
  method     = var.method
  response_header = var.response_header
  max_age_seconds = var.max_age_seconds
 }
}
```

### Panic Output
```
module.xxx.google_storage_bucket.default: Modifying... [id=chs-dev-exp-rewardspts-img]
module.xxx.google_storage_bucket.default: Modifying... [id=chs-dev-apple-rewardspts-img]
╷
│ Error: Plugin did not respond
│ 
│   with module.xxx.google_storage_bucket.default,
│   on .terraform/modules/xxx/modules/gcs-backend-bucket-xlb/bucket.tf line 5, in resource "google_storage_bucket" "default":
│    5: resource "google_storage_bucket" "default" {
│ Error: Request cancelled
│   on .terraform/modules/xxx/modules/gcs-backend-bucket-xlb/bucket.tf line 5, in resource "google_storage_bucket" "default":
│    5: resource "google_storage_bucket" "default" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-google_v4.74.0_x5 plugin:


goroutine 191 [running]:
github.com/hashicorp/terraform-provider-google/google/services/storage.expandCors({0xc0020f8aa0, 0x1, 0xc001affce0?})
    github.com/hashicorp/terraform-provider-google/google/services/storage/resource_storage_bucket.go:942 +0x44f
github.com/hashicorp/terraform-provider-google/google/services/storage.resourceStorageBucketUpdate(0x0?, {0x317f8e0?, 0xc001175b00})
    github.com/hashicorp/terraform-provider-google/google/services/storage/resource_storage_bucket.go:673 +0xa1f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x37df9d8?, {0x37df9d8?, 0xc0014dbd40?}, 0xd?, {0x317f8e0?, 0xc001175b00?})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000ae15e0, {0x37df9d8, 0xc0014dbd40}, 0xc00204da00, 0xc001de7e00, {0x317f8e0, 0xc001175b00})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006d96f8, {0x37df9d8?, 0xc0014dbc20?}, 0xc000fba8c0)
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000af30e0, 0xc000af3140, {0xc0010e9600, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
    github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000b54640, {0x37df9d8?, 0xc0014db350?}, 0xc002038af0)
    github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x3103b80?, 0xc000b54640}, {0x37df9d8, 0xc0014db350}, 0xc002038a80, 0x0)
    github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000b625a0, {0x37e7ca0, 0xc000a7c340}, 0xc001fdcc60, 0xc000938d80, 0x4b02a40, 0x0)
    google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc000b625a0, {0x37e7ca0, 0xc000a7c340}, 0xc001fdcc60, 0x0)
    google.golang.org/grpc@v1.56.1/server.go:1714 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
    google.golang.org/grpc@v1.56.1/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
    google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

Error: The terraform-provider-google_v4.74.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

##[error]Error: The process '/opt/hostedtoolcache/terraform/1.4.6/x64/terraform' failed with exit code 1
Finishing: Terraform Apply
```
### Expected Behavior

CORS should have been applied on GCS bucket.

### Actual Behavior

Exception is being thrown

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

b/302672590

**Comment by edwardmedia** [comment]
@kanhaPrayas can you share the repro steps?

**Comment by edwardmedia** [comment]
@kanhaPrayas can you repro this issue? If yes, can you share the steps?

**Comment by agutta** [comment]
@edwardmedia  - Steps to reproduce

1) Create a GCS Bucket
2) Add cors block with all empty values

```
cors{
        origin = []
        method = []
        response_header = []
    }
 ```

**Comment by kautikdk** [comment]
@shuyama1, I think this can be solved by adding one validation and sanitization logic for empty cors configuration and empty individual fields. All of the fields in the cors block are optional and can be provided empty. Though I am not sure why this the case from backend side but it is allowing empty cors configuration. To mitigate it from the client side we can use DiffSuppressFunc to suppress terraform diff of empty cors block and values and simultaneously removing it from the configuration in cors expanders. 
As per the API behavior we can pass empty `cors {}` block and it won't result in any error. We won't get empty `cors {}` block back from the response and because of that we have to use DiffSuppressFunc. Let me know if that's the correct way to handle this issue, Will raise PR accordingly. 
I was thinking is to use `AtLeastOneOf` to force user to provide at least one of the cors configuration field. Empty cors block doesn't make any sense but this won't be consistent with API behavior as of now So we can hold it as it is for now.
