### ISSUE TITLE
TF plan the plugin.(*GRPCProvider).ReadResource request was cancelled.

### ISSUE THREAD

**Issue by herokri** [hashicorp/terraform-provider-google#15436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Initializing provider plugins...
- Finding hashicorp/google versions matching "~> 4.76.0"...
- Finding hashicorp/google-beta versions matching "~> 4.76.0"...
- Installing hashicorp/google-beta v4.76.0...
- Installed hashicorp/google-beta v4.76.0 (signed by HashiCorp)
- Installing hashicorp/google v4.76.0...
- Installed hashicorp/google v4.76.0 (signed by HashiCorp)

### Affected Resource(s)

* google_dataplex

### Terraform Configuration Files

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform planned the following actions, but then encountered a problem:

  # google_dataplex_datascan.qs-ds_xxxxxxxxxxxxxxxx will be created
  + resource "google_dataplex_datascan" "xxxxxxxxxxxxxx" {
      + create_time         = (known after apply)
      + data_profile_result = (known after apply)
      + data_quality_result = (known after apply)
      + data_scan_id        = "xxxxxxxxxxxxxxxxxxxx"
      + description         = "Prod challenge Profile"
      + display_name        = "Prod challenge Profile"
      + execution_status    = (known after apply)
      + id                  = (known after apply)
      + labels              = {
          + "domain" = "xxxxxxxxxxxxxx"
          + "owner"  = "xxxxxxxxxxx"
          + "unit"   = "xxxxxxxx"
        }
      + location            = "europe-west3"
      + name                = (known after apply)
      + project             = "rapid-ferret-6dfe"
      + state               = (known after apply)
      + type                = (known after apply)
      + uid                 = (known after apply)
      + update_time         = (known after apply)

      + data {
          + resource = "//bigquery.googleapis.com/projects/xxxxxxxxxxxxxxxx/datasets/ds_sla_xx/tables/t_prd_challenge"
        }

      + data_quality_spec {
          + rules {
              + dimension = "VALIDITY"

              + table_condition_expectation {
                  + sql_expression = "COUNT(*) > 0"
                }
            }
          + rules {
              + column    = "challengeIdentifier"
              + dimension = "UNIQUENESS"

              + uniqueness_expectation {}
            }
        }

      + execution_spec {
          + field = "ds_nodash"

          + trigger {
              + on_demand {}
            }
        }
    }

  # google_dataplex_xxxxxxxxxxxxxxxxxx will be destroyed
  # (because google_dataplex_dxxxxxxxxxxxxxx is not in configuration)
  - resource "google_dataplex_datascan" "xxxxxxxxxxxxxxxx" {
      - create_time         = "2023-08-07T07:06:43.405812221Z" -> null
      - data_profile_result = [] -> null
      - data_quality_result = [
          - {
              - dimensions   = [
                  - {
                      - passed = true
                    },
                ]
              - passed       = true
              - row_count    = "500"
              - rules        = [
                  - {
                      - evaluated_count    = "500"
                      - failing_rows_query = ""
                      - null_count         = ""
                      - pass_ratio         = 0
                      - passed             = true
                      - passed_count       = ""
                      - rule               = [
                          - {
                              - column                      = ""
                              - dimension                   = "VALIDITY"
                              - ignore_null                 = false
                              - non_null_expectation        = []
                              - range_expectation           = []
                              - regex_expectation           = []
                              - row_condition_expectation   = []
                              - set_expectation             = []
                              - statistic_range_expectation = []
                              - table_condition_expectation = [
                                  - {
                                      - sql_expression = "COUNT(*) > 0"
                                    },
                                ]
                              - threshold                   = 0
                              - uniqueness_expectation      = []
                            },
                        ]
                    },
                ]
              - scanned_data = [
                  - {
                      - incremental_field = [
                          - {
                              - end   = "2023-08-04"
                              - field = "ds_nodash"
                              - start = ""
                            },
                        ]
                    },
                ]
            },
        ] -> null
      - data_scan_id        = "quality-scan-sla-t-prd-challenge" -> null
      - description         = "Prod challenge Profile" -> null
      - display_name        = "Prod challenge Profile" -> null
      - execution_status    = [
          - {
              - latest_job_end_time   = "2023-08-08T11:11:21.648939614Z"
              - latest_job_start_time = "2023-08-08T11:10:52.901472172Z"
            },
        ] -> null
      - id                  = "projects/xxxxxxxxxxxxxxxx/locations/europe-west3/dataScans/xxxxxxxxxxxxx" -> null
      - labels              = {
          - "domain" = "xxxxxxxxxxx"
          - "owner"  = "xxxxl"
          - "unit"   = "xxxxxxxxxxxx"
        } -> null
      - location            = "europe-west3" -> null
      - name                = "projects/xxxxxxx/locations/europe-west3/dataScans/yyyyyyyyyyyyyyyyyyyy" -> null
      - project             = "xxxxx" -> null
      - state               = "ACTIVE" -> null
      - type                = "DATA_QUALITY" -> null
      - uid                 = "8b061866-e016-47e1-8a3d-d77eca60d04c" -> null
      - update_time         = "2023-08-08T08:00:20.130288177Z" -> null

      - data {
          - resource = "//bigquery.googleapis.com/projects/xxxxxx/datasets/ds_sla_xx/tables/t_prd_challenge" -> null
        }

      - data_quality_spec {
          - sampling_percent = 0 -> null

          - rules {
              - dimension   = "VALIDITY" -> null
              - ignore_null = false -> null
              - threshold   = 0 -> null

              - table_condition_expectation {
                  - sql_expression = "COUNT(*) > 0" -> null
                }
            }
        }

      - execution_spec {
          - field = "ds_nodash" -> null

          - trigger {
              - on_demand {}
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.

### Debug Output

Error: Request cancelled

  with google_dataplex_datascan.profile-sla-t-prd-challenge,
  on profile_sla_t_prd_challenge.tf line 1, in resource "google_dataplex_datascan" "profile-sla-t-prd-challenge":
   1: resource "google_dataplex_datascan" "profile-sla-t-prd-challenge" {

The plugin.(*GRPCProvider).ReadResource request was cancelled.

Stack trace from the terraform-provider-google_v4.76.0_x5 plugin:

panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 203 [running]:
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResultProfileFieldsProfileTopNValues(...)
	github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2239
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResultProfileFieldsProfile({0x31f6c60?, 0xc000d02450}, 0x37a1fa2?, 0x7?)
	github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2192 +0x5f3
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResultProfileFields({0x2fa0260?, 0xc001274210?}, 0x379fd03?, 0x6?)
	github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2161 +0x305
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResultProfile({0x31f6c60?, 0xc000d023c0}, 0x37a1fa2?, 0x7?)
	github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2142 +0xa5
github.com/hashicorp/terraform-provider-google/google/services/dataplex.flattenDataplexDatascanDataProfileResult({0x31f6c60?, 0xc000d02390}, 0x37beb3a?, 0x11?)
	github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:2123 +0x11e
github.com/hashicorp/terraform-provider-google/google/services/dataplex.resourceDataplexDatascanRead(0xc0006d8b80, {0x3771300?, 0xc000193600})
	github.com/hashicorp/terraform-provider-google/google/services/dataplex/resource_dataplex_datascan.go:1138 +0x1307
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x3e5f7d8?, {0x3e5f7d8?, 0xc000e95590?}, 0xd?, {0x3771300?, 0xc000193600?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000789880, {0x3e5f7d8, 0xc000e95590}, 0xc001824c30, {0x3771300, 0xc000193600})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000c5d998, {0x3e5f7d8?, 0xc000e95470?}, 0xc0010ca400)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc000c09c50, 0xc000c09cb0, {0xc0012decc0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000410c80, {0x3e5f7d8?, 0xc000e94030?}, 0xc001320120)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x36e6800?, 0xc000410c80}, {0x3e5f7d8, 0xc000e94030}, 0xc001808000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0011e21e0, {0x3e686c0, 0xc000d70680}, 0xc00124e120, 0xc00131bef0, 0x55d82f0, 0x0)
	google.golang.org/grpc@v1.56.2/server.go:1337 +0xdf0
google.golang.org/grpc.(*Server).handleStream(0xc0011e21e0, {0x3e686c0, 0xc000d70680}, 0xc00124e120, 0x0)
	google.golang.org/grpc@v1.56.2/server.go:1714 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.2/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.2/server.go:957 +0x18c

Error: The terraform-provider-google_v4.76.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior

terraform plan runs

### Actual Behavior

terraform plan chrashes

### Steps to Reproduce

we can destroy all resources and restart, when it works

1. `terraform apply`

### References

* #0000

**Comment by edwardmedia** [comment]
@herokri can you repro this? Please share the config and repro steps?

**Comment by c2thorn** [comment]
I believe https://github.com/GoogleCloudPlatform/magic-modules/pull/8578 is attempting to fix this.

**Comment by ggtisc** [comment]
@herokri could you share the code to reproduce the issue, or confirm if it was solved?

**Comment by Joseluismantilla** [comment]
GRPC error was solved by using a higher Azure provider version -- the 3.97.0
