### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by engmgc21** [hashicorp/terraform-provider-google#15847]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

* Terraform core version: v1.4.5
* Provider: hashicorp/google-beta v4.82.0

### Affected Resource(s)

* google_container_node_pool

### Terraform Configuration Files

```
resource "google_container_node_pool" "gke-nodepool" {
  for_each = {for np in local.cluster_node_pools : np.pool_name => np}
  project = var.gcp_project
  name       = each.value["pool_name"]
  location   = var.region
  cluster    = each.value["cluster_name"]
  node_count = each.value["node_pool_size"]

  autoscaling {
    location_policy = "BALANCED"
    min_node_count  = each.value["node_pool_min"]
    max_node_count  = each.value["node_pool_max"]
  }

  node_config {
    machine_type = each.value["node_machine_type"]
    disk_size_gb = each.value["node_disk_size_gb"]
    image_type   = each.value["node_image"]
    service_account = var.gke_nodes_sa_email
    min_cpu_platform = each.value["min_cpu_platform"]
    dynamic "linux_node_config" {
      for_each = length(each.value["sysctl_config"]) > 0 ? each.value["sysctl_config"] : []
      content {
        sysctls = linux_node_config.value
      }
    }
    oauth_scopes    = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
    tags = ["${var.site_name}-gke-nodes"]
  }
  management {
    auto_repair  = false
    auto_upgrade = true
  }
  depends_on = [google_container_cluster.site-cluster]
  lifecycle {
    ignore_changes = []
  }
}

```
### Panic Output

```
Stack trace from the terraform-provider-google_v4.82.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 481 [running]:
github.com/hashicorp/terraform-provider-google/google/services/container.expandLinuxNodeConfig(...)
	github.com/hashicorp/terraform-provider-google/google/services/container/node_config.go:905
github.com/hashicorp/terraform-provider-google/google/services/container.expandNodeConfig({0x10574fb80?, 0x14001798ed0?})
	github.com/hashicorp/terraform-provider-google/google/services/container/node_config.go:827 +0x1740
github.com/hashicorp/terraform-provider-google/google/services/container.expandNodePool(0x105f93ea0?, {0x0, 0x0})
	github.com/hashicorp/terraform-provider-google/google/services/container/resource_container_node_pool.go:858 +0x2e8
github.com/hashicorp/terraform-provider-google/google/services/container.resourceContainerNodePoolCreate(0x140026c8780, {0x105f2d2a0?, 0x14001159200?})
	github.com/hashicorp/terraform-provider-google/google/services/container/resource_container_node_pool.go:472 +0x120
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x105f8b078?, {0x105f8b078?, 0x1400110aab0?}, 0xd?, {0x105f2d2a0?, 0x14001159200?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:695 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000daa380, {0x105f8b078, 0x1400110aab0}, 0x14000e1ca90, 0x140026c8600, {0x105f2d2a0, 0x14001159200})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000e4d950, {0x105f8b078?, 0x1400110a990?}, 0x14001087b80)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0x14000e0cd50, 0x14000e0cdb0, {0x1400150b0e0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400066c140, {0x105f8b078?, 0x1400110a120?}, 0x140015c8230)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x105ea2aa0?, 0x1400066c140}, {0x105f8b078, 0x1400110a120}, 0x140015c81c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001921e0, {0x105f93fc0, 0x140005fa680}, 0x14001679320, 0x1400055de00, 0x1076cb3e0, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xc88
google.golang.org/grpc.(*Server).handleStream(0x140001921e0, {0x105f93fc0, 0x140005fa680}, 0x14001679320, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-google_v4.82.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Expected Behavior

* Successful creation of nodepool

### Actual Behavior

* Panic error on apply

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* The use case is to be able to support different nodepool config through the same module. We have some clusters that need linux sysctl node config for kernel parameter tuning while others do not.

### References

* #0000

b/300616618

**Comment by edwardmedia** [comment]
@engmgc21 can you share the debug log that contains the api requests and responses? If you can repro, can you share the steps to reach that point?

**Comment by engmgc21** [comment]
Here's the debug error log [](url)
[gcp_tf_error.log](https://github.com/hashicorp/terraform-provider-google/files/12612484/gcp_tf_error.log)

**Comment by engmgc21** [comment]
Adding reference: https://github.com/hashicorp/terraform-provider-aws/issues/24881

Unfortunately cannot provide debug log because of sensitive info. You can use the code snippet to reproduce, just need to have a nodepool with sysctl_config key set to [{}]. If the sysctl_config key is empty then the dynamic block for linux_config sets

` linux_node_config {}
`
Apply and nodepool creation will work if you have some sysctl parameters defined e.g.:

```
sysctl_config = [{
    "net.ipv4.tcp_tw_reuse" = "x"
    "net.core.somaxconn" = "abcd"
  }]

```

This will set the linux config to:
```

linux_node_config {
              + sysctls = {
                  + "net.core.somaxconn"    = "abcd"
                  + "net.ipv4.tcp_tw_reuse" = "x"
                }
            }
```
