### ISSUE TITLE
Error: The terraform-provider-google_v5.0.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by StefanoAgostinelliHW** [hashicorp/terraform-provider-google#16125]
Hi everyone!
When I launched the apply of a newly imported GKE cluster I received a provider error (you will find the logs, the module, the plans and the apply below).
The module was also used to import other clusters and it didn't give me any problems.
I remain available to answer any doubts or provide additional details.
Thank you in advance for your help.

Stephen

### Terraform Version

Leatest at the time of writing

```
Terraform v1.5.7
on windows_amd64
+ provider [registry.terraform.io/hashicorp/google](http://registry.terraform.io/hashicorp/google) v5.0.0
+ provider [registry.terraform.io/hashicorp/google-beta](http://registry.terraform.io/hashicorp/google-beta) v5.0.0
```

### Affected Resource(s)

google_container_node_pool

### Terraform Configuration Files

https://docs.google.com/document/d/1pIgu8J2e0OqsNyrgId8fEvGHxYsyOOvb3f4EJXe2Qbg/edit?usp=sharing

### Debug Output

https://docs.google.com/document/d/1uLS_RuxJ19Yt6v4OGxMtN9frJxBrPECIx0IK9shiFMM/edit?usp=sharing

### Expected Behavior

```
  # module.gke_faas.google_container_node_pool.node_pools["workers-a"] will be updated in-place
  ~ resource "google_container_node_pool" "node_pools" {
        id                          = "projects/<project_name>/locations/europe-west1-d/clusters/faas-v2-dev/nodePools/workers-a"
        name                        = "workers-a"
        # (10 unchanged attributes hidden)

      + autoscaling {}

      - timeouts {}

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual Behavior

```
│ Error: Plugin did not respond
│
│   with module.gke_inf3.google_container_node_pool.node_pools["inf3-dev-workers-b"],
│   on ..\..\iacn-custom-modules\module-gke\[main.tf](http://main.tf/) line 68, in resource "google_container_node_pool" "node_pools":
│   68: resource "google_container_node_pool" "node_pools" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may       
│ contain more details.
╵

Stack trace from the terraform-provider-google_v5.0.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 247 [running]:
[github.com/hashicorp/terraform-provider-google/google/services/container.nodePoolUpdate(0xc001fb2d80](http://github.com/hashicorp/terraform-provider-google/google/services/container.nodePoolUpdate%280xc001fb2d80), {0x3f1fe00?, 0xc00199e900}, 0xc00176ce40, {0x0, 0x0}, 0x1a3185c5000)
        [github.com/hashicorp/terraform-provider-google/google/services/container/resource_container_node_pool.go:1180](http://github.com/hashicorp/terraform-provider-google/google/services/container/resource_container_node_pool.go:1180) +0x4774
[github.com/hashicorp/terraform-provider-google/google/services/container.resourceContainerNodePoolUpdate(0xc001fb2d80](http://github.com/hashicorp/terraform-provider-google/google/services/container.resourceContainerNodePoolUpdate%280xc001fb2d80), {0x3f1fe00?, 0xc00199e900?})
        [github.com/hashicorp/terraform-provider-google/google/services/container/resource_container_node_pool.go:667](http://github.com/hashicorp/terraform-provider-google/google/services/container/resource_container_node_pool.go:667) +0x354
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x4660078](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.%28*Resource%29.update%280x4660078)?, {0x4660078?, 0xc0016a6d50?}, 0xd?, {0x3f1fe00?, 0xc00199e900?})
        [github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:729](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:729) +0x178
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000dfcfc0](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.%28*Resource%29.Apply%280xc000dfcfc0), {0x4660078, 0xc0016a6d50}, 0xc00211c000, 0xc001fb2b00, {0x3f1fe00, 0xc00199e900})
        [github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:847](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:847) +0x83a
[github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000008198](http://github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.%28*GRPCProviderServer%29.ApplyResourceChange%280xc000008198), {0x4660078?, 0xc0016a6c30?}, 0xc001160820)
        [github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021](http://github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021) +0xe8d
[github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc000e942d0](http://github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange%28%7B0xc000e942d0), 0xc000e94330, {0xc000d0dfe0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        [github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27](http://github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ApplyResourceChange.go:27) +0x102
[github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001e4be0](http://github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.%28*server%29.ApplyResourceChange%280xc0001e4be0), {0x4660078?, 0xc0016a61b0?}, 0xc00114abd0)
        [github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818](http://github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818) +0x574
[github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x3e96c00](http://github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler%28%7B0x3e96c00)?, 0xc0001e4be0}, {0x4660078, 0xc0016a61b0}, 0xc00114ab60, 0x0)
        [github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385](http://github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385) +0x170
[google.golang.org/grpc.(*Server).processUnaryRPC(0xc0013b45a0](http://google.golang.org/grpc.%28*Server%29.processUnaryRPC%280xc0013b45a0), {0x46690a0, 0xc000cba1a0}, 0xc0011afc20, 0xc00130f1a0, 0x5e3a5e0, 0x0)      
        [google.golang.org/grpc@v1.57.0/server.go:1360](http://google.golang.org/grpc@v1.57.0/server.go:1360) +0xe23
[google.golang.org/grpc.(*Server).handleStream(0xc0013b45a0](http://google.golang.org/grpc.%28*Server%29.handleStream%280xc0013b45a0), {0x46690a0, 0xc000cba1a0}, 0xc0011afc20, 0x0)
        [google.golang.org/grpc@v1.57.0/server.go:1737](http://google.golang.org/grpc@v1.57.0/server.go:1737) +0xa2f
[google.golang.org/grpc.(*Server).serveStreams.func1.1()](http://google.golang.org/grpc.%28*Server%29.serveStreams.func1.1%28%29)
        [google.golang.org/grpc@v1.57.0/server.go:982](http://google.golang.org/grpc@v1.57.0/server.go:982) +0x98
created by [google.golang.org/grpc.(*Server).serveStreams.func1](http://google.golang.org/grpc.%28*Server%29.serveStreams.func1)
        [google.golang.org/grpc@v1.57.0/server.go:980](http://google.golang.org/grpc@v1.57.0/server.go:980) +0x18c

Error: The terraform-provider-google_v5.0.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

I haven't found a way to replicate the error in other environments.

Terraform init
Terraform import
Terraform apply

### Important Factoids

The GKE cluster use out-to-date Kubernetes APIs. once you log into the console you get the following warning:
<img width="505" alt="image" src="https://github.com/hashicorp/terraform-provider-google/assets/117460612/e2999b9a-5b68-448d-b267-90ccb73f7aa1">

**Comment by rileykarson** [comment]
I think this has happened for pretty much forever, unless we just relaxed a validation on autoscaling recently. We're missing a nil check on a 6 year old line of code. I'll send a fix tomorrow- GKE was angry with my test environment and provisioning a cluster took a bit.

**Comment by rileykarson** [comment]
This should only get triggered if specifically `autoscaling {}` is specified in Terraform (including if fields are specified explicitly as null) and any other permutation should not trigger it.

**Comment by rileykarson** [comment]
@ScottSuarez see https://github.com/hashicorp/terraform-provider-google/issues/16125#issuecomment-1749744754 for what's happening here. We should verify that `autoscaling {}` has reasonable results.
