### ISSUE TITLE
Terraform-provider-google_v5.14.0_x5 plugin crashed

### ISSUE THREAD

**Issue by devuonocar** [hashicorp/terraform-provider-google#17177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team)
  to expedite investigation and resolution of this issue.

### Terraform Version

1.5.2

### Affected Resource(s)

data.google_container_cluster

### Terraform Configuration

```
data "google_container_cluster" "gke_cluster" {
  name     = "gke_cluster"  
  location = "europe-west3"
  project  = "project_id"
}
```

### Expected Behavior

Read GKE cluster data correctly 

### Actual Behavior

│ Error: Plugin did not respond
│ 
│   with module.prometheus_server.data.google_container_cluster.gke_cluster,
│   on external-modules/prometheus_bundle/main.tf line 46, in data "google_container_cluster" "gke_cluster":
│   46: data "google_container_cluster" "gke_cluster" {

│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.

│ Error: Plugin did not respond
│ 
│   with module.prometheus_proxy_new.data.google_container_cluster.gke_cluster,
│   on external-modules/prometheus_bundle/main.tf line 46, in data "google_container_cluster" "gke_cluster":
│   46: data "google_container_cluster" "gke_cluster" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.

Stack trace from the terraform-provider-google_v5.14.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x31b7459]

goroutine 581 [running]:
github.com/hashicorp/terraform-provider-google/google/services/container.resourceContainerClusterRead(0xc001a50a80?, {0x3bf4ba0?, 0xc000671500})
	github.com/hashicorp/terraform-provider-google/google/services/container/resource_container_cluster.go:2469 +0x1879
github.com/hashicorp/terraform-provider-google/google/services/container.datasourceContainerClusterRead(0xc001a50a80, {0x3bf4ba0?, 0xc000671500})
	github.com/hashicorp/terraform-provider-google/google/services/container/data_source_google_container_cluster.go:48 +0x1c5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x43243b8?, {0x43243b8?, 0xc001077b30?}, 0xd?, {0x3bf4ba0?, 0xc000671500?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0006056c0, {0x43243b8, 0xc001077b30}, 0xc001a50980, {0x3bf4ba0, 0xc000671500})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000a9a8e8, {0x43243b8?, 0xc001077a10?}, 0xc00211c320)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadDataSource({0xc0005aac60, 0xc0005aacc0, {0xc000eef680, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadDataSource.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0016fa460, {0x43243b8?, 0xc001077200?}, 0xc000f7c910)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:658 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x3b66d80?, 0xc0016fa460}, {0x43243b8, 0xc001077200}, 0xc001a50600, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0015ed000, {0x43243b8, 0xc001077170}, {0x432dc58, 0xc001787d40}, 0xc002128360, 0xc0005aa720, 0x5c5f030, 0x0)
	google.golang.org/grpc@v1.60.1/server.go:1372 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc0015ed000, {0x432dc58, 0xc001787d40}, 0xc002128360)
	google.golang.org/grpc@v1.60.1/server.go:1783 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.1/server.go:1016 +0x68
created by google.golang.org/grpc.(*Server).serveStreams.func2
	google.golang.org/grpc@v1.60.1/server.go:1027 +0x12e

Error: The terraform-provider-google_v5.14.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

script returned exit code 1

### Steps to reproduce

1. `terraform plan`

**Comment by devuonocar** [comment]
Hi @trodge I saw that similar issues have been found in the past for older provider versions. Do we have a chance to solve it? Sorry but is blocking important activities.

**Comment by devuonocar** [comment]
I do not know why, but the issue seems solved. Today, the `terraform plan` did not show again the problem. You can close the issue, and thank you for the support.

**Comment by devuonocar** [comment]
I do not know why, but the issue seems solved. Today, the terraform plan did not show again the problem. I'll close the issue, and thanks for the support.
