### ISSUE TITLE
Failing test(s): TestAccAppEngineFlexibleAppVersion_update (panic)

### ISSUE THREAD

**Issue by SarahFrench** [hashicorp/terraform-provider-google#17203]
### Failure rates

- 2 panic failures since 2024-01-01

### Impacted tests

- TestAccAppEngineFlexibleAppVersion_update

### Affected Resource(s)

* google_app_engine_flexible_app_version

### Nightly build test history

- [Link](https://hashicorp.teamcity.com/test/7385344304796565941?currentProjectId=TerraformProviders_Google_NightlyTests&expandTestHistoryChartSection=true)

### Message(s)

`flattenAppEngineFlexibleAppVersionDeployment`

```
Test ended in panic.
------- Stdout: -------
=== RUN   TestAccAppEngineFlexibleAppVersion_update
=== PAUSE TestAccAppEngineFlexibleAppVersion_update
=== CONT  TestAccAppEngineFlexibleAppVersion_update
------- Stderr: -------
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc00109e680] Closing: EOF
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc00109e680] loopyWriter exiting with error: transport closed by client
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc001c32340] Closing: EOF
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc00107a4e0] Closing: EOF
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc001c32340] loopyWriter exiting with error: transport closed by client
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc00107a4e0] loopyWriter exiting with error: transport closed by client
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc00287c000] Closing: EOF
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc00287c000] Closing: EOF
2024/02/07 05:25:21 [DEBUG] [transport] [server-transport 0xc0005d8340] Closing: EOF
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc001698000] Closing: EOF
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc001699860] Closing: EOF
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc001699860] loopyWriter exiting with error: transport closed by client
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc001698000] loopyWriter exiting with error: transport closed by client
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc00287c1a0] Closing: EOF
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc00287c1a0] loopyWriter exiting with error: transport closed by client
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc0005d8d00] Closing: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: read unix /opt/teamcity-agent/temp/buildTmp/plugin3531288747->@: read: connection reset by peer"
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc001c32340] Closing: EOF
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc001c32340] loopyWriter exiting with error: transport closed by client
2024/02/07 05:25:22 [DEBUG] [transport] [server-transport 0xc000c48b60] Closing: EOF
2024/02/07 05:25:23 [DEBUG] [transport] [server-transport 0xc000e56340] Closing: EOF
2024/02/07 05:33:35 [DEBUG] [transport] [server-transport 0xc000e56000] Closing: EOF
2024/02/07 05:33:35 [DEBUG] [transport] [server-transport 0xc000bd6ea0] Closing: EOF
2024/02/07 05:33:35 [DEBUG] [transport] [server-transport 0xc000e56000] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:35 [DEBUG] [transport] [server-transport 0xc000bd6ea0] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:35 [DEBUG] [transport] [server-transport 0xc0012b84e0] Closing: EOF
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc001f94820] Closing: EOF
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc001f94820] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc0010c8000] Closing: EOF
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc000f781a0] Closing: EOF
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc0005d8340] Closing: EOF
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc000f78340] Closing: EOF
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc000f78000] Closing: EOF
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc0005d84e0] Closing: EOF
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc000f78340] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc000f78000] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:36 [DEBUG] [transport] [server-transport 0xc0005d84e0] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:37 [DEBUG] [transport] [server-transport 0xc0022f4d00] Closing: EOF
2024/02/07 05:33:37 [DEBUG] [transport] [server-transport 0xc000db09c0] Closing: EOF
2024/02/07 05:33:37 [DEBUG] [transport] [server-transport 0xc000db09c0] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:37 [DEBUG] [transport] [server-transport 0xc0023e2000] Closing: EOF
2024/02/07 05:33:37 [DEBUG] [transport] [server-transport 0xc0023e2000] Closing: EOF
2024/02/07 05:33:37 [DEBUG] [transport] [server-transport 0xc0023e2680] Closing: EOF
2024/02/07 05:33:42 [DEBUG] [transport] [server-transport 0xc0023e2820] Closing: EOF
2024/02/07 05:33:42 [DEBUG] [transport] [server-transport 0xc0023e2340] Closing: EOF
2024/02/07 05:33:42 [DEBUG] [transport] [server-transport 0xc0023e2820] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:42 [DEBUG] [transport] [server-transport 0xc0023e2340] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:42 [DEBUG] [transport] [server-transport 0xc0023e21a0] Closing: EOF
2024/02/07 05:33:42 [DEBUG] [transport] [server-transport 0xc0023e21a0] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:42 [DEBUG] [transport] [server-transport 0xc002521ba0] Closing: EOF
2024/02/07 05:33:42 [DEBUG] [transport] [server-transport 0xc001699a00] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc001a4ed00] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc002521d40] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc001a4e1a0] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc002520340] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc002521d40] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc001a4e1a0] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc002520340] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc0022f4820] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc0022f49c0] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc0022f49c0] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc00156c000] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc00149c000] Closing: EOF
2024/02/07 05:33:43 [DEBUG] [transport] [server-transport 0xc00149c000] loopyWriter exiting with error: transport closed by client
2024/02/07 05:33:44 [DEBUG] [transport] [server-transport 0xc001824000] Closing: EOF
2024/02/07 05:33:44 [DEBUG] [transport] [server-transport 0xc0017da000] Closing: EOF
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 4015 [running]:
github.com/hashicorp/terraform-provider-google/google/services/appengine.flattenAppEngineFlexibleAppVersionDeployment({0x0?, 0x0?}, 0x3db634d?, 0xa?)
  /opt/teamcity-agent/work/7efd395a0500e5ad/google/services/appengine/resource_app_engine_flexible_app_version.go:2020 +0x5ad
github.com/hashicorp/terraform-provider-google/google/services/appengine.resourceAppEngineFlexibleAppVersionRead(0xc0012bae00, {0x3d7cf00?, 0xc00237d500})
  /opt/teamcity-agent/work/7efd395a0500e5ad/google/services/appengine/resource_app_engine_flexible_app_version.go:1212 +0x12a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x44f0998?, {0x44f0998?, 0xc00110d950?}, 0xd?, {0x3d7cf00?, 0xc00237d500?})
  /var/lib/teamcity/go/1.20.13/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0009f8620, {0x44f0998, 0xc00110d950}, 0xc0015015f0, {0x3d7cf00, 0xc00237d500})
  /var/lib/teamcity/go/1.20.13/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00151dfe0, {0x44f0998?, 0xc00110d5f0?}, 0xc0021fb840)
  /var/lib/teamcity/go/1.20.13/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc00153ef60, 0xc00153efc0, {0xc001b7a420, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
  /var/lib/teamcity/go/1.20.13/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0010cd900, {0x44f0998?, 0xc00110cab0?}, 0xc002234720)
  /var/lib/teamcity/go/1.20.13/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x3ceb840?, 0xc0010cd900}, {0x44f0998, 0xc00110cab0}, 0xc0012bab00, 0x0)
  /var/lib/teamcity/go/1.20.13/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00195ba00, {0x44f0998, 0xc00110ca20}, {0x44fa678, 0xc00149c000}, 0xc001d37320, 0xc0016f6f30, 0x5ef8e10, 0x0)
  /var/lib/teamcity/go/1.20.13/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1372 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc00195ba00, {0x44fa678, 0xc00149c000}, 0xc001d37320)
  /var/lib/teamcity/go/1.20.13/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1783 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
  /var/lib/teamcity/go/1.20.13/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1016 +0x68
created by google.golang.org/grpc.(*Server).serveStreams.func2
  /var/lib/teamcity/go/1.20.13/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1027 +0x12e
```

b/325031757

**Comment by SarahFrench** [comment]
The panic has only happened twice, and the test has passed between both panics so it might be due to the contents of the API responses?

**Comment by afafara** [comment]
We've hit this issue on production while trying to deploy a new version:

```
Stack trace from the terraform-provider-google_v5.15.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 408 [running]:
github.com/hashicorp/terraform-provider-google/google/services/appengine.flattenAppEngineFlexibleAppVersionDeployment({0x0?, 0x0?}, 0x107855afc?, 0xa?)
        github.com/hashicorp/terraform-provider-google/google/services/appengine/resource_app_engine_flexible_app_version.go:2020 +0x558
github.com/hashicorp/terraform-provider-google/google/services/appengine.resourceAppEngineFlexibleAppVersionRead(0x140007bfe00, {0x108929d40?, 0x140001e6000})
        github.com/hashicorp/terraform-provider-google/google/services/appengine/resource_app_engine_flexible_app_version.go:1212 +0xe80
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x108987c78?, {0x108987c78?, 0x140011a9a70?}, 0xd?, {0x108929d40?, 0x140001e6000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:712 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000bd3180, {0x108987c78, 0x140011a9a70}, 0x14000f90b60, {0x108929d40, 0x140001e6000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x46c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140011019e0, {0x108987c78?, 0x140011a9950?}, 0x14002202d00)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0x140010ceb10, 0x140010ceb70, {0x14001a049c0, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0xdc
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14000136140, {0x108987c78?, 0x140011a9140?}, 0x14001dcc960)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x10889bce0?, 0x14000136140}, {0x108987c78, 0x140011a9140}, 0x140007bf580, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140017e4800, {0x108987c78, 0x140011a90b0}, {0x108991438, 0x1400195a820}, 0x1400154cb40, 0x14001ae9320, 0x10a234f50, 0x0)
        google.golang.org/grpc@v1.60.1/server.go:1372 +0xc6c
google.golang.org/grpc.(*Server).handleStream(0x140017e4800, {0x108991438, 0x1400195a820}, 0x1400154cb40)
        google.golang.org/grpc@v1.60.1/server.go:1783 +0xc9c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.1/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.60.1/server.go:1027 +0x148

Error: The terraform-provider-google_v5.15.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

It seems that Google API is returning inconsistent responses, so it sometimes works and sometimes not.
Difference is in `createTime` timestamp and `createdBy` field (missing).

Diff of working json response for AppEngline flexible:
```
{
  "createTime": "2024-02-06T15:42:59Z",
  "createdBy": "some@service-account.com"
}
```
response that fails:
```
{
  "createTime": "2024-02-06T15:42:52.762069133Z"
  // Note: 'createdBy' field is missing
}
```

Response was from same version. As you can see the timestamp format was different, but also it is off by couple of seconds.

**Comment by Shumicorp** [comment]
I have the same issue when deploying the new version:
```
Stack trace from the terraform-provider-google_v5.20.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 114 [running]:
github.com/hashicorp/terraform-provider-google/google/services/appengine.flattenAppEngineFlexibleAppVersionDeployment({0x0?, 0x0?}, 0x3d7b26e?, 0xa?)
        github.com/hashicorp/terraform-provider-google/google/services/appengine/resource_app_engine_flexible_app_version.go:2020 +0x5ad
github.com/hashicorp/terraform-provider-google/google/services/appengine.resourceAppEngineFlexibleAppVersionRead(0xc001791180, {0x3d43000?, 0xc000234000})
        github.com/hashicorp/terraform-provider-google/google/services/appengine/resource_app_engine_flexible_app_version.go:1212 +0x12a5
github.com/hashicorp/terraform-provider-google/google/services/appengine.resourceAppEngineFlexibleAppVersionCreate(0xc001791180, {0x3d43000?, 0xc000234000})
        github.com/hashicorp/terraform-provider-google/google/services/appengine/resource_app_engine_flexible_app_version.go:1103 +0x466d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x44aa018?, {0x44aa018?, 0xc00116dcb0?}, 0xd?, {0x3d43000?, 0xc000234000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000a07500, {0x44aa018, 0xc00116dcb0}, 0xc000eee0d0, 0xc001791000, {0x3d43000, 0xc000234000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006c9338, {0x44aa018?, 0xc00116db90?}, 0xc001914780)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x44a9f70?, {0x44aa018?, 0xc00116d860?}, 0xc001914780)
        github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0005a4640, {0x44aa018?, 0xc00116ced0?}, 0xc0019e2000)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x3ce0c40?, 0xc0005a4640}, {0x44aa018, 0xc00116ced0}, 0xc001790b80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001bd800, {0x44aa018, 0xc00116ce40}, {0x44b3f18, 0xc0005cc340}, 0xc0014e4240, 0xc000f51f20, 0x5e6de18, 0x0)
        google.golang.org/grpc@v1.61.1/server.go:1385 +0xe49
google.golang.org/grpc.(*Server).handleStream(0xc0001bd800, {0x44b3f18, 0xc0005cc340}, 0xc0014e4240)
        google.golang.org/grpc@v1.61.1/server.go:1796 +0x1031
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.61.1/server.go:1029 +0x91
created by google.golang.org/grpc.(*Server).serveStreams.func2
        google.golang.org/grpc@v1.61.1/server.go:1040 +0x145

Error: The terraform-provider-google_v5.20.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
Usually, the deployment of the version succeeds on the second attempt

**Comment by ealebed** [comment]
The same for me...

**Comment by Witcher94** [comment]
Same....

**Comment by maksymsereda** [comment]
Have the same situation. Do anyone know how to fix that?
