### ISSUE TITLE
Unable to make provider change with magic-module

### ISSUE THREAD

**Issue by hassannmoussaa** [hashicorp/terraform-provider-google#18046]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform vX.X.X
on <architecture>
+ provider registry.terraform.io/hashicorp/google vX.X.X
+ provider registry.terraform.io/hashicorp/google-beta vX.X.X

### Affected Resource(s)

make provider VERSION=ga OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google" PRODUCT=compute

### Terraform Configuration

```tf
```
Command i run : make provider VERSION=ga OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google" PRODUCT=compute

### Debug Output

bundler: failed to load command: compiler.rb (compiler.rb)
/root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:455:in `parse': (<unknown>): did not find expected '-' indicator while parsing a block collection at line 504 column 7 (Psych::SyntaxError)
	from /root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:455:in `parse_stream'
	from /root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:399:in `parse'
	from /root/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:324:in `safe_load'
	from /home/magic-modules/mmv1/google/yaml_validator.rb:25:in `parse'
	from /home/magic-modules/mmv1/api/compiler.rb:28:in `run'
	from compiler.rb:189:in `block (2 levels) in <top (required)>'
	from compiler.rb:178:in `each'
	from compiler.rb:178:in `block in <top (required)>'
	from /root/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'

### Expected Behavior

working fine 

### Steps to reproduce

1. `terraform apply`

**Comment by NickElliot** [comment]
Hi -- just to make sure your environment for MMV1 development is totally clean could you do the following:
1. rebase your current local mmv1 branch on main
2. checkout a clean version of the terraform-provider-google head

If running the command again fails, could you share your output of running the following 2 commands in your cli?
`ruby -v`
`rbenv versions`
