### ISSUE TITLE
Plugin Error - strconv.ParseInt value out of range

### ISSUE THREAD

**Issue by larsenqec** [hashicorp/terraform-provider-google#18569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to a user, that user is claiming responsibility for the issue.
* Customers working with a Google Technical Account Manager or Customer Engineer can ask them to [reach out internally](https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team) to expedite investigation and resolution of this issue.

### Terraform Version & Provider Version(s)

Terraform v1.8.4
on win64
+ provider registry.terraform.io/hashicorp/google v5.33.0

### Affected Resource(s)

google_storage_bucket

### Terraform Configuration

```tf
//Project Provider
provider "google" {
  project     = var.project
  region      = var.region
  zone        = var.zone
}

// Service Backend
terraform {
  backend "gcs" {
    bucket  = "quicksilver-osrm-state"
    prefix  = "storage"
  }
}

// Buckets
resource "google_storage_bucket" "osrm_storage" {
  name          = "osrm-storage"
  storage_class = "STANDARD"
  location      = var.region
  force_destroy = false
}
```

### Debug Output

```
google_storage_bucket.osrm_storage: Refreshing state... [id=osrm-storage]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│ 
│   with google_storage_bucket.osrm_storage,
│   on main.tf line 17, in resource "google_storage_bucket" "osrm_storage":
│   17: resource "google_storage_bucket" "osrm_storage" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-google_v5.33.0_x5.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "463259780931": value out of range

goroutine 49 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x1029ab90, {0xfeccd98, 0x1, 0x1}, 0x8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource_data.go:556 +0x299
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x1029ab90)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource_data.go:354 +0x463
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x10325810, {{{0x4e7f8bc, 0x1042bfb0}}, {0x41a0740, 0x10437bc0}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:670 +0x1e8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x10571ee0, {0x4e7f49c, 0x1098d7e8}, 0x10436ce0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:641 +0x238
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0xfd0eaa0, {0x4e7f49c, 0x1098d710}, 0x10436ce0)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ReadResource.go:35 +0x1df
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xfd0ee10, {0x4e7f49c, 0x1098d440}, 0x10992ae0)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov5/tf5server/server.go:775 +0x4b3
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x4708100, 0xfd0ee10}, {0x4e7f49c, 0x1098d440}, 0x1005a840, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x176
google.golang.org/grpc.(*Server).processUnaryRPC(0xfcb8c80, {0x4e7f49c, 0x1098d410}, {0x4e848c4, 0x10184200}, 0x10aed0e0, 0xfd09bc0, 0x69379b4, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xf89
google.golang.org/grpc.(*Server).handleStream(0xfcb8c80, {0x4e848c4, 0x10184200}, 0x10aed0e0)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x1108
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 25
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x13f

Error: The terraform-provider-google_v5.33.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Expected Behavior

Plan should have shown no-changes required

### Actual Behavior

error thrown -- see output above

### Steps to reproduce

1. `terraform plan`

**Comment by ggtisc** [comment]
Hi @larsenqec!

Please run a `terraform -version`, share with us the result of the system version and the system you are using(x64 or x86t) to verify if both versions match.

**Comment by larsenqec** [comment]
![image](https://github.com/hashicorp/terraform-provider-google/assets/52664234/7829e32f-a9cc-4561-b31e-0238ee15d390)

**Comment by larsenqec** [comment]
Oh, I guess I had the 32 bit binary. But maybe that's still an unexpected bug.

**Comment by ggtisc** [comment]
Yes, you can find more information about these kinds of situations [here](https://github.com/hashicorp/terraform-provider-google/issues/6518).

I recommend you to be sure that both versions (terraform and system) match to avoid this kind of issues. A 64-bit binary like windows_amd64, to prevent this from coming up again.
