### ISSUE TITLE
Terraform error 

### ISSUE THREAD

**Issue by ACenterA-SLNet** [hashicorp/terraform-provider-google#7318]
We used the google provider using terraform 0.13.beta2 successfully for various elements.

Now we wanted to use terraform 0.13.3 (to support multiple provider with the latest fixes)

But now we have error about data and also the following. Not sure what this error is linked to.

Using 

```
resource "google_compute_url_map" "test" {
...
}
```

```
google_compute_url_map.s3: Refreshing state... [id=projects/xxxxxxxxxx/global/urlMaps/url-map-target-proxy]
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: panic: Error reading level state: strconv.ParseInt: parsing "6501599534966138000": value out of range
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: goroutine 657 [running]:
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).get(0xc0c4180, 0xc410840, 0x1, 0x1, 0xc175508, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.11.0/helper/schema/resource_data.go:540 +0x293
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).State(0xc0c4180, 0xbda7110)
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.11.0/helper/schema/resource_data.go:338 +0x29c
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ShimInstanceStateFromValue(0xbe4fe00, 0xa27b9e0, 0xc32bd50, 0x9a2bee0, 0xc172980, 0xa27b9e0, 0xc32bd50, 0x9a2bee0)
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.11.0/helper/schema/resource.go:196 +0x157
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc116008, 0xa27b1a0, 0xc65c160, 0xbda6090, 0xc116008, 0x1, 0xc65c160)
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.11.0/internal/helper/plugin/grpc_provider.go:510 +0x1d3
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x9dd03e0, 0xc116008, 0xa27b1a0, 0xc65c160, 0xbda6060, 0x0, 0xa27b1a0, 0xc65c160, 0xc2f9400, 0x490)
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.11.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x195
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xbfb66c0, 0xa288480, 0xbe7be00, 0xc5f2000, 0xc06b740, 0xb0d1e88, 0x0, 0x0, 0x0)
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:1180 +0x4ed
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: google.golang.org/grpc.(*Server).handleStream(0xbfb66c0, 0xa288480, 0xbe7be00, 0xc5f2000, 0x0)
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:1503 +0xa7d
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0a22b0, 0xbfb66c0, 0xa288480, 0xbe7be00, 0xc5f2000)
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:843 +0x8a
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-09-21T16:37:42.379-0400 [DEBUG] plugin.terraform-provider-google_v3.39.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.31.1/server.go:841 +0x1b0
2020/09/21 16:37:42 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/09/21 16:37:42 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/09/21 16:37:42 [TRACE] [walkRefresh] Exiting eval tree: google_compute_url_map.test
```

**Comment by ACenterA-SLNet** [comment]
Wrong, 32 bit binary? :/
