### ISSUE TITLE
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call.

### ISSUE THREAD

**Issue by flightlesstux** [hashicorp/terraform-provider-google#9030]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version
```
terraform -v
Terraform v0.15.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v3.66.0
+ provider registry.terraform.io/hashicorp/google-beta v3.66.0
```

### Affected Resource(s)
* google_compute_instance_template
* google_comoute_instance_group
* google_compute_instance

### Terraform Configuration Files

```tf
Default configiration from https://registry.terraform.io/providers/hashicorp/google/latest/docs
```

### Panic Output

```
Stack trace from the terraform-provider-google_v3.66.0_x5 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 213 [running]:
github.com/hashicorp/terraform-provider-google/google.serviceAccountDiffSuppress(0x14000bd9e80, 0x1a, 0x104880d57, 0x1, 0x104880d58, 0x1, 0x14000978f80, 0x1053a4500)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/resource_compute_instance.go:2248 +0x340
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0x1400089c990, 0x10484a317, 0xf, 0x140008b7e00, 0x14000cfc520, 0x1054f2fc8, 0x14000978f80, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/schema.go:972 +0x2bc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x1400089c990, 0x1054c32e0, 0x14000963600, 0x1400037f880, 0x14000bedad0, 0x14000079d80, 0x105429dc0, 0x1400034b800, 0x104e06200, 0x1062ac520, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/schema.go:522 +0x1b0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x140008ad260, 0x1054c32e0, 0x14000963600, 0x1400037f880, 0x14000bedad0, 0x105429dc0, 0x1400034b800, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:506 +0x68
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0x14000698fd8, 0x1054c32e0, 0x14000963600, 0x14000bc2dc0, 0x14000963600, 0x10537d820, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:693 +0x654
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0x14000cfd9a0, 0x1054c3388, 0x14000963600, 0x1400037f730, 0x14000cfd9a0, 0x1030eaa60, 0x1051e7520)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:315 +0x94
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x10537d820, 0x14000cfd9a0, 0x1054c3388, 0x140010ff260, 0x1400103a420, 0x0, 0x1054c3388, 0x140010ff260, 0x1400017a000, 0x8eb)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001fe540, 0x1054fb498, 0x14000001c80, 0x1400007e900, 0x1400089da40, 0x106268d28, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1217 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x140001fe540, 0x1054fb498, 0x14000001c80, 0x1400007e900, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1540 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000688820, 0x140001fe540, 0x1054fb498, 0x14000001c80, 0x1400007e900)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:878 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:876 +0x1f8

Error: The terraform-provider-google_v3.66.0_x5 plugin crashed!
```

### Expected Behavior
`Plan: 16 to add, 0 to change, 0 to destroy.`

### Actual Behavior
```
│ Error: Plugin did not respond
│
│   with google_compute_instance_template.this,
│   on instance_template.tf line 1, in resource "google_compute_instance_template" "this":
│    1: resource "google_compute_instance_template" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with data.google_compute_instance_group.this,
│   on main.tf line 48, in data "google_compute_instance_group" "this":
│   48: data "google_compute_instance_group" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with google_compute_instance.this,
│   on vm-instance-for-image.tf line 1, in resource "google_compute_instance" "this":
│    1: resource "google_compute_instance" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
```

### Steps to Reproduce
1. `terraform plan`

### References
https://registry.terraform.io/providers/hashicorp/google/latest/docs

**Comment by flightlesstux** [comment]
@megan07 @rileykarson Hello, module version `3.65.0` also is working, and now, I've tested on `3.66.1` the issue is solved.
