### ISSUE TITLE
Terraform plan fails with service_account block for google_compute_instance resource

### ISSUE THREAD

**Issue by softveda** [hashicorp/terraform-provider-google#9039]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.66.0

### Affected Resource(s)

* google_compute_instance

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.66.0"
    }
  }
}
provider "google" {
  project = "XXX"
  region  = "us-central1"
  zone    = "us-central1-c"
}

resource "google_compute_network" "vpc_network" {
  name = "terraform-network"
}

resource "google_compute_instance" "vminstance" {
  name         = "vault-01"
  machine_type = "n1-standard-1"
  boot_disk {
    initialize_params {
      image = "ubuntu/ubuntu-20.04"
    }
  }
  metadata = {
    ssh-keys = "XXX"
  }
  network_interface {
    access_config {
    }
    network = google_compute_network.vpc_network.self_link
  }
  allow_stopping_for_update = true
  service_account {
    email  = "gcloud-cli@XXX.iam.gserviceaccount.com"
    scopes = ["cloud-platform"]
  }

}
```

### Debug Output
2021-04-30T15:39:07.202+1000 [DEBUG] Adding temp file log sink: /var/folders/kz/xw0fm7fd6mz5rjmq40kbm6k80000gp/T/terraform-log544316463
2021-04-30T15:39:07.202+1000 [INFO]  Terraform version: 0.15.1
2021-04-30T15:39:07.202+1000 [INFO]  Go runtime version: go1.16.2
2021-04-30T15:39:07.202+1000 [INFO]  CLI args: []string{"/usr/local/bin/terraform", "plan", "-no-color"}
2021-04-30T15:39:07.202+1000 [DEBUG] Attempting to open CLI config file: /Users/pkhasnabis/.terraformrc
2021-04-30T15:39:07.202+1000 [INFO]  Loading CLI configuration from /Users/pkhasnabis/.terraformrc
2021-04-30T15:39:07.202+1000 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021-04-30T15:39:07.203+1000 [DEBUG] ignoring non-existing provider search directory /Users/pkhasnabis/.terraform.d/plugins
2021-04-30T15:39:07.203+1000 [DEBUG] ignoring non-existing provider search directory /Users/pkhasnabis/Library/Application Support/io.terraform/plugins
2021-04-30T15:39:07.203+1000 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2021-04-30T15:39:07.203+1000 [INFO]  CLI command args: []string{"plan", "-no-color"}
2021-04-30T15:39:07.205+1000 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2021-04-30T15:39:08.217+1000 [DEBUG] Retrieve version constraints for service tfe.v2.1 and product terraform
2021-04-30T15:39:10.377+1000 [DEBUG] checking for provisioner in "."
2021-04-30T15:39:10.385+1000 [DEBUG] checking for provisioner in "/usr/local/bin"
2021-04-30T15:39:10.385+1000 [INFO]  Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2021-04-30T15:39:11.423+1000 [INFO]  backend/local: starting Plan operation
2021-04-30T15:39:13.732+1000 [DEBUG] created provider logger: level=debug
2021-04-30T15:39:13.732+1000 [INFO]  provider: configuring client automatic mTLS
2021-04-30T15:39:13.773+1000 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 args=[.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5]
2021-04-30T15:39:13.779+1000 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 pid=37195
2021-04-30T15:39:13.779+1000 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5
2021-04-30T15:39:13.806+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: configuring server automatic mTLS: timestamp=2021-04-30T15:39:13.805+1000
2021-04-30T15:39:13.845+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: plugin address: address=/var/folders/kz/xw0fm7fd6mz5rjmq40kbm6k80000gp/T/plugin541709470 network=unix timestamp=2021-04-30T15:39:13.845+1000
2021-04-30T15:39:13.845+1000 [DEBUG] provider: using plugin: version=5
2021-04-30T15:39:13.925+1000 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-30T15:39:13.927+1000 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 pid=37195
2021-04-30T15:39:13.927+1000 [DEBUG] provider: plugin exited
2021-04-30T15:39:13.927+1000 [INFO]  terraform: building graph: GraphTypeValidate
2021-04-30T15:39:13.927+1000 [DEBUG] ProviderTransformer: "google_compute_network.vpc_network" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/hashicorp/google"]
2021-04-30T15:39:13.927+1000 [DEBUG] ProviderTransformer: "google_compute_instance.vminstance" (*terraform.NodeValidatableResource) needs provider["registry.terraform.io/hashicorp/google"]
2021-04-30T15:39:13.928+1000 [DEBUG] ReferenceTransformer: "google_compute_network.vpc_network" references: []
2021-04-30T15:39:13.928+1000 [DEBUG] ReferenceTransformer: "google_compute_instance.vminstance" references: [google_compute_network.vpc_network]
2021-04-30T15:39:13.928+1000 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/hashicorp/google\"]" references: []
2021-04-30T15:39:13.928+1000 [DEBUG] Starting graph walk: walkValidate
2021-04-30T15:39:13.929+1000 [DEBUG] created provider logger: level=debug
2021-04-30T15:39:13.929+1000 [INFO]  provider: configuring client automatic mTLS
2021-04-30T15:39:13.959+1000 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 args=[.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5]
2021-04-30T15:39:13.969+1000 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 pid=37196
2021-04-30T15:39:13.969+1000 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5
2021-04-30T15:39:13.991+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: configuring server automatic mTLS: timestamp=2021-04-30T15:39:13.990+1000
2021-04-30T15:39:14.026+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: plugin address: address=/var/folders/kz/xw0fm7fd6mz5rjmq40kbm6k80000gp/T/plugin047480787 network=unix timestamp=2021-04-30T15:39:14.026+1000
2021-04-30T15:39:14.026+1000 [DEBUG] provider: using plugin: version=5
2021-04-30T15:39:14.136+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:14 [WARN] Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-04-30T15:39:14.136+1000
2021-04-30T15:39:14.137+1000 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-30T15:39:14.139+1000 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 pid=37196
2021-04-30T15:39:14.139+1000 [DEBUG] provider: plugin exited
2021-04-30T15:39:14.140+1000 [INFO]  backend/local: plan calling Plan
2021-04-30T15:39:14.140+1000 [INFO]  terraform: building graph: GraphTypePlan
2021-04-30T15:39:14.140+1000 [DEBUG] ProviderTransformer: "google_compute_network.vpc_network (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/hashicorp/google"]
2021-04-30T15:39:14.140+1000 [DEBUG] ProviderTransformer: "google_compute_instance.vminstance (expand)" (*terraform.nodeExpandPlannableResource) needs provider["registry.terraform.io/hashicorp/google"]
2021-04-30T15:39:14.140+1000 [DEBUG] ReferenceTransformer: "provider[\"registry.terraform.io/hashicorp/google\"]" references: []
2021-04-30T15:39:14.140+1000 [DEBUG] ReferenceTransformer: "google_compute_network.vpc_network (expand)" references: []
2021-04-30T15:39:14.140+1000 [DEBUG] ReferenceTransformer: "google_compute_instance.vminstance (expand)" references: [google_compute_network.vpc_network (expand)]
2021-04-30T15:39:14.141+1000 [DEBUG] Starting graph walk: walkPlan
2021-04-30T15:39:14.141+1000 [DEBUG] created provider logger: level=debug
2021-04-30T15:39:14.141+1000 [INFO]  provider: configuring client automatic mTLS
2021-04-30T15:39:14.174+1000 [DEBUG] provider: starting plugin: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 args=[.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5]
2021-04-30T15:39:14.181+1000 [DEBUG] provider: plugin started: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 pid=37197
2021-04-30T15:39:14.181+1000 [DEBUG] provider: waiting for RPC address: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5
2021-04-30T15:39:14.206+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: configuring server automatic mTLS: timestamp=2021-04-30T15:39:14.206+1000
2021-04-30T15:39:14.246+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: plugin address: address=/var/folders/kz/xw0fm7fd6mz5rjmq40kbm6k80000gp/T/plugin114643960 network=unix timestamp=2021-04-30T15:39:14.246+1000
2021-04-30T15:39:14.246+1000 [DEBUG] provider: using plugin: version=5
2021-04-30T15:39:14.352+1000 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/hashicorp/google\"]" changed the config value, but that value is unused
2021-04-30T15:39:14.354+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:14 [INFO] Authenticating using configured Google JSON 'credentials'...: timestamp=2021-04-30T15:39:14.354+1000
2021-04-30T15:39:14.354+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:14 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]: timestamp=2021-04-30T15:39:14.354+1000
2021-04-30T15:39:14.354+1000 [DEBUG] ReferenceTransformer: "google_compute_network.vpc_network" references: []
google_compute_network.vpc_network: Refreshing state... [id=projects/pratik-sandbox/global/networks/terraform-network]
2021-04-30T15:39:14.356+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:14 [DEBUG] Waiting for state to become: [success]: timestamp=2021-04-30T15:39:14.356+1000
2021-04-30T15:39:14.356+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:14 [DEBUG] Retry Transport: starting RoundTrip retry loop: timestamp=2021-04-30T15:39:14.356+1000
2021-04-30T15:39:14.356+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:14 [DEBUG] Retry Transport: request attempt 0: timestamp=2021-04-30T15:39:14.356+1000
2021-04-30T15:39:14.356+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:14 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
GET /compute/v1/projects/pratik-sandbox/global/networks/terraform-network?alt=json HTTP/1.1
Host: compute.googleapis.com
User-Agent: Terraform/0.15.1 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/dev
Content-Type: application/json
Accept-Encoding: gzip

-----------------------------------------------------: timestamp=2021-04-30T15:39:14.356+1000
2021-04-30T15:39:15.331+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:15 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Fri, 30 Apr 2021 05:39:15 GMT
Etag: Dp01OhhKVu9yBDIQKHe91kANW5k=/2cqcGaQ1eVSKsyKAaFjC92bbKts=
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "id": "5662430683749341598",
  "creationTimestamp": "2021-04-29T19:12:01.283-07:00",
  "name": "terraform-network",
  "selfLink": "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/global/networks/terraform-network",
  "autoCreateSubnetworks": true,
  "subnetworks": [
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/us-west2/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/asia-northeast1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/us-west1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/asia-east1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/us-central1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/southamerica-east1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/us-east1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/asia-northeast3/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/europe-west4/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/europe-north1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/australia-southeast1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/asia-southeast1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/us-west3/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/northamerica-northeast1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/asia-east2/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/asia-northeast2/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/us-west4/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/asia-southeast2/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/europe-west2/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/europe-west1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/asia-south1/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/europe-west6/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/us-east4/subnetworks/terraform-network",
    "https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/europe-central2/subnetworks/terraform-network",
"https://www.googleapis.com/compute/v1/projects/pratik-sandbox/regions/europe-west3/subnetworks/terraform-network"
  ],
  "routingConfig": {
    "routingMode": "REGIONAL"
  },
  "kind": "compute#network"
}

-----------------------------------------------------: timestamp=2021-04-30T15:39:15.331+1000
2021-04-30T15:39:15.331+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:15 [DEBUG] Retry Transport: Stopping retries, last request was successful: timestamp=2021-04-30T15:39:15.331+1000
2021-04-30T15:39:15.331+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:15 [DEBUG] Retry Transport: Returning after 1 attempts: timestamp=2021-04-30T15:39:15.331+1000
2021-04-30T15:39:15.334+1000 [WARN]  Provider "registry.terraform.io/hashicorp/google" produced an invalid plan for google_compute_network.vpc_network, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .auto_create_subnetworks: planned value cty.True for a non-computed attribute
      - .delete_default_routes_on_create: planned value cty.False for a non-computed attribute
      - .description: planned value cty.StringVal("") for a non-computed attribute
2021-04-30T15:39:15.335+1000 [DEBUG] Resource instance state not found for node "google_compute_instance.vminstance", instance google_compute_instance.vminstance
2021-04-30T15:39:15.335+1000 [DEBUG] ReferenceTransformer: "google_compute_instance.vminstance" references: []
2021-04-30T15:39:15.335+1000 [DEBUG] refresh: google_compute_instance.vminstance: no state, so not refreshing
2021-04-30T15:39:15.337+1000 [INFO]  provider.terraform-provider-google_v3.66.0_x5: 2021/04/30 15:39:15 [WARN] Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-04-30T15:39:15.336+1000
2021-04-30T15:39:15.340+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: PANIC: interface conversion: interface {} is *schema.Set, not []interface {}
2021-04-30T15:39:15.340+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5:
2021-04-30T15:39:15.340+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: goroutine 129 [running]:
2021-04-30T15:39:15.340+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: github.com/hashicorp/terraform-provider-google/google.serviceAccountDiffSuppress(0xc00118a880, 0x1a, 0x3924275, 0x1, 0x3924276, 0x1, 0xc000347580, 0x203000)
2021-04-30T15:39:15.340+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/resource_compute_instance.go:2248 +0x425
2021-04-30T15:39:15.340+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc000b61290, 0x38ed805, 0xf, 0xc00026d2c0, 0xc001170dc0, 0x3dae9a8, 0xc000347580, 0x0, 0x0, 0x0)
2021-04-30T15:39:15.340+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/schema.go:972 +0x383
2021-04-30T15:39:15.340+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000b61290, 0x3d7ef60, 0xc0000d0f40, 0xc000d304d0, 0xc000c6b7d0, 0xc0000f2a40, 0x38b8a00, 0xc0003ad800, 0x4ba3900, 0x32949c0, ...)
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/schema.go:522 +0x219
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc000542b60, 0x3d7ef60, 0xc0000d0f40, 0xc000d304d0, 0xc000c6b7d0, 0x38b8a00, 0xc0003ad800, 0x0, 0x0, 0x0)
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:506 +0xa5
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0000c70b0, 0x3d7ef60, 0xc0000d0f40, 0xc000e083c0, 0xc0000d0f40, 0x380c1e0, 0xc000f22f00)
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:693 +0x7c5
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc0010e2e80, 0x3d7f008, 0xc0000d0f40, 0xc000d30380, 0xc0010e2e80, 0xc000f22f00, 0xc0002f2ba0)
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:315 +0xb5
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x380c1e0, 0xc0010e2e80, 0x3d7f008, 0xc000f22f00, 0xc00116cc60, 0x0, 0x3d7f008, 0xc000f22f00, 0xc00002bb00, 0xd3b)
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00052b180, 0x3db6d58, 0xc000193680, 0xc00116e200, 0xc000f22540, 0x4b5ff88, 0x0, 0x0, 0x0)
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1217 +0x52b
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc00052b180, 0x3db6d58, 0xc000193680, 0xc00116e200, 0x0)
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1540 +0xd0c
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00003a310, 0xc00052b180, 0x3db6d58, 0xc000193680, 0xc00116e200)
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:878 +0xab
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-30T15:39:15.341+1000 [DEBUG] provider.terraform-provider-google_v3.66.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:876 +0x1fd
2021-04-30T15:39:15.344+1000 [ERROR] plugin.(*GRPCProvider).PlanResourceChange: error="rpc error: code = Unavailable desc = transport is closing"
2021-04-30T15:39:15.344+1000 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-04-30T15:39:15.344+1000 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/google/3.66.0/darwin_amd64/terraform-provider-google_v3.66.0_x5 pid=37197 error="exit status 2"
2021-04-30T15:39:15.345+1000 [INFO]  backend/local: plan operation completed

Error: Plugin did not respond

  with google_compute_instance.vminstance,
  on main.tf line 26, in resource "google_compute_instance" "vminstance":
  26: resource "google_compute_instance" "vminstance" {

The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.

Stack trace from the terraform-provider-google_v3.66.0_x5 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 129 [running]:
github.com/hashicorp/terraform-provider-google/google.serviceAccountDiffSuppress(0xc00118a880, 0x1a, 0x3924275, 0x1, 0x3924276, 0x1, 0xc000347580, 0x203000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-google/google/resource_compute_instance.go:2248 +0x425
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc000b61290, 0x38ed805, 0xf, 0xc00026d2c0, 0xc001170dc0, 0x3dae9a8, 0xc000347580, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/schema.go:972 +0x383
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000b61290, 0x3d7ef60, 0xc0000d0f40, 0xc000d304d0, 0xc000c6b7d0, 0xc0000f2a40, 0x38b8a00, 0xc0003ad800, 0x4ba3900, 0x32949c0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/schema.go:522 +0x219
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0xc000542b60, 0x3d7ef60, 0xc0000d0f40, 0xc000d304d0, 0xc000c6b7d0, 0x38b8a00, 0xc0003ad800, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:506 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).PlanResourceChange(0xc0000c70b0, 0x3d7ef60, 0xc0000d0f40, 0xc000e083c0, 0xc0000d0f40, 0x380c1e0, 0xc000f22f00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:693 +0x7c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).PlanResourceChange(0xc0010e2e80, 0x3d7f008, 0xc0000d0f40, 0xc000d30380, 0xc0010e2e80, 0xc000f22f00, 0xc0002f2ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:315 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x380c1e0, 0xc0010e2e80, 0x3d7f008, 0xc000f22f00, 0xc00116cc60, 0x0, 0x3d7f008, 0xc000f22f00, 0xc00002bb00, 0xd3b)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:362 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00052b180, 0x3db6d58, 0xc000193680, 0xc00116e200, 0xc000f22540, 0x4b5ff88, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00052b180, 0x3db6d58, 0xc000193680, 0xc00116e200, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00003a310, 0xc00052b180, 0x3db6d58, 0xc000193680, 0xc00116e200)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.36.0/server.go:876 +0x1fd

Error: The terraform-provider-google_v3.66.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2021-04-30T15:39:15.636+1000 [DEBUG] provider: plugin exited

### Expected Behavior

Terraform plan should succeed

### Actual Behavior

Terraform plan failed

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
* The previous terraform applied create the compute_network resource named vpc_network
* This run was supposed to provision the compute instance VM
* The plan succeeds if the service_account block is commented out
* The service account has been pre-created manually

**Comment by edwardmedia** [comment]
@softveda closing the issue then. Please reopen if it is still an issue
