### ISSUE TITLE
Error: The terraform-provider-vcd_v3.3.1.exe plugin crashed!  VMware/vcloud director 

### ISSUE THREAD

**Issue by Reham-Fahmy** [hashicorp/terraform-provider-google#9550]
While trying to run the terraform code as iaas using VMware/vcloud director version 10.1.2 ,terraform 1.0.1 and vcd plugin is 3.3.1
it shows me the below error(I removed sensitive data and names)and nothing is created on vcloud director.

terraform apply -var-file=
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[1m  # vcd_edgegateway.-ESG[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "vcd_edgegateway" "ESG" {
      [32m+[0m [0m[1m[0mconfiguration[0m[0m                   = "Quad Large"
      [32m+[0m [0m[1m[0mdefault_external_network_ip[0m[0m     = (known after apply)
      [32m+[0m [0m[1m[0mdescription[0m[0m                     = "This is used by  org"
      [32m+[0m [0m[1m[0mdistributed_routing[0m[0m             = false
      [32m+[0m [0m[1m[0mexternal_network_ips[0m[0m            = (known after apply)
      [32m+[0m [0m[1m[0mfips_mode_enabled[0m[0m               = false
      [32m+[0m [0m[1m[0mfw_default_rule_action[0m[0m          = "deny"
      [32m+[0m [0m[1m[0mfw_default_rule_logging_enabled[0m[0m = false
      [32m+[0m [0m[1m[0mfw_enabled[0m[0m                      = true
      [32m+[0m [0m[1m[0mha_enabled[0m[0m                      = false
      [32m+[0m [0m[1m[0mid[0m[0m                              = (known after apply)
      [32m+[0m [0m[1m[0mlb_acceleration_enabled[0m[0m         = false
      [32m+[0m [0m[1m[0mlb_enabled[0m[0m                      = false
      [32m+[0m [0m[1m[0mlb_logging_enabled[0m[0m              = false
      [32m+[0m [0m[1m[0mlb_loglevel[0m[0m                     = "info"
      [32m+[0m [0m[1m[0mname[0m[0m                            = "ESG"
      [32m+[0m [0m[1m[0morg[0m[0m                             = ""
      [32m+[0m [0m[1m[0muse_default_route_for_dns_relay[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mvdc[0m[0m                             = ""

      [32m+[0m [0mexternal_network {
          [32m+[0m [0m[1m[0menable_rate_limit[0m[0m   = false
          [32m+[0m [0m[1m[0mincoming_rate_limit[0m[0m = 0
          [32m+[0m [0m[1m[0mname[0m[0m                = "Ext_net0"
          [32m+[0m [0m[1m[0moutgoing_rate_limit[0m[0m = 0

          [32m+[0m [0msubnet {
              [32m+[0m [0m[1m[0mgateway[0m[0m               = "/28"
              [32m+[0m [0m[1m[0mip_address[0m[0m            = ""
              [32m+[0m [0m[1m[0mnetmask[0m[0m               = "255.255.255.239"
              [32m+[0m [0m[1m[0muse_for_default_route[0m[0m = true
            }
        }
    }

[1m  # vcd_network_routed.-Internal-Network[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "vcd_network_routed" "-Internal-Network" {
      [32m+[0m [0m[1m[0mdescription[0m[0m  = "This is an internal  Network "
      [32m+[0m [0m[1m[0medge_gateway[0m[0m = "ESG"
      [32m+[0m [0m[1m[0mgateway[0m[0m      = "192.168.10.1"
      [32m+[0m [0m[1m[0mhref[0m[0m         = (known after apply)
      [32m+[0m [0m[1m[0mid[0m[0m           = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m         = "Internal-Network"
      [32m+[0m [0m[1m[0mnetmask[0m[0m      = "255.255.255.0"
      [32m+[0m [0m[1m[0morg[0m[0m          = ""
      [32m+[0m [0m[1m[0mshared[0m[0m       = false
      [32m+[0m [0m[1m[0mvdc[0m[0m          = ""

      [32m+[0m [0mstatic_ip_pool {
          [32m+[0m [0m[1m[0mend_address[0m[0m   = "192.168.10.254"
          [32m+[0m [0m[1m[0mstart_address[0m[0m = "192.168.10.2"
        }
    }

[1m  # vcd_org.org[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "vcd_org" "org" {
      [32m+[0m [0m[1m[0mcan_publish_catalogs[0m[0m = true
      [32m+[0m [0m[1m[0mdelete_force[0m[0m         = false
      [32m+[0m [0m[1m[0mdelete_recursive[0m[0m     = false
      [32m+[0m [0m[1m[0mdeployed_vm_quota[0m[0m    = 1000
      [32m+[0m [0m[1m[0mdescription[0m[0m          = "This is via Terraform for Tenant"
      [32m+[0m [0m[1m[0mfull_name[0m[0m            = ""
      [32m+[0m [0m[1m[0mid[0m[0m                   = (known after apply)
      [32m+[0m [0m[1m[0mis_enabled[0m[0m           = true
      [32m+[0m [0m[1m[0mname[0m[0m                 = ""
      [32m+[0m [0m[1m[0mstored_vm_quota[0m[0m      = 1000

      [32m+[0m [0mvapp_lease {
          [32m+[0m [0m[1m[0mdelete_on_storage_lease_expiration[0m[0m    = false
          [32m+[0m [0m[1m[0mmaximum_runtime_lease_in_sec[0m[0m          = 0
          [32m+[0m [0m[1m[0mmaximum_storage_lease_in_sec[0m[0m          = 0
          [32m+[0m [0m[1m[0mpower_off_on_runtime_lease_expiration[0m[0m = false
        }

      [32m+[0m [0mvapp_template_lease {
          [32m+[0m [0m[1m[0mdelete_on_storage_lease_expiration[0m[0m = false
          [32m+[0m [0m[1m[0mmaximum_storage_lease_in_sec[0m[0m       = 0
        }
    }

[1m  # vcd_org_user.[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "vcd_org_user" "" {
      [32m+[0m [0m[1m[0mdeployed_vm_quota[0m[0m = 1000
      [32m+[0m [0m[1m[0menabled[0m[0m           = true
      [32m+[0m [0m[1m[0mid[0m[0m                = (known after apply)
      [32m+[0m [0m[1m[0mis_group_role[0m[0m     = false
      [32m+[0m [0m[1m[0mname[0m[0m              = ""
      [32m+[0m [0m[1m[0morg[0m[0m               = ""
      [32m+[0m [0m[1m[0mpassword[0m[0m          = (sensitive value)
      [32m+[0m [0m[1m[0mprovider_type[0m[0m     = "INTEGRATED"
      [32m+[0m [0m[1m[0mrole[0m[0m              = "Organization Administrator"
      [32m+[0m [0m[1m[0mstored_vm_quota[0m[0m   = 1000
      [32m+[0m [0m[1m[0mtake_ownership[0m[0m    = true
    }

[1m  # vcd_org_vdc.-VDC[0m will be created[0m[0m
[0m  [32m+[0m[0m resource "vcd_org_vdc" "-VDC" {
      [32m+[0m [0m[1m[0mallocation_model[0m[0m            = "AllocationPool"
      [32m+[0m [0m[1m[0mallow_over_commit[0m[0m           = (known after apply)
      [32m+[0m [0m[1m[0mcpu_guaranteed[0m[0m              = (known after apply)
      [32m+[0m [0m[1m[0mcpu_speed[0m[0m                   = (known after apply)
      [32m+[0m [0m[1m[0mdefault_vm_sizing_policy_id[0m[0m = (known after apply)
      [32m+[0m [0m[1m[0mdelete_force[0m[0m                = false
      [32m+[0m [0m[1m[0mdelete_recursive[0m[0m            = false
      [32m+[0m [0m[1m[0melasticity[0m[0m                  = (known after apply)
      [32m+[0m [0m[1m[0menable_fast_provisioning[0m[0m    = true
      [32m+[0m [0m[1m[0menable_thin_provisioning[0m[0m    = false
      [32m+[0m [0m[1m[0menabled[0m[0m                     = true
      [32m+[0m [0m[1m[0mid[0m[0m                          = (known after apply)
      [32m+[0m [0m[1m[0minclude_vm_memory_overhead[0m[0m  = (known after apply)
      [32m+[0m [0m[1m[0mmemory_guaranteed[0m[0m           = (known after apply)
      [32m+[0m [0m[1m[0mname[0m[0m                        = ""
      [32m+[0m [0m[1m[0mnetwork_pool_name[0m[0m           = "Ext_net0"
      [32m+[0m [0m[1m[0mnetwork_quota[0m[0m               = 1000
      [32m+[0m [0m[1m[0morg[0m[0m                         = ""
      [32m+[0m [0m[1m[0mprovider_vdc_name[0m[0m           = "PVDC_old"
      [32m+[0m [0m[1m[0mvm_sizing_policy_ids[0m[0m        = (known after apply)

      [32m+[0m [0mcompute_capacity {
          [32m+[0m [0mcpu {
              [32m+[0m [0m[1m[0mallocated[0m[0m = 1024
              [32m+[0m [0m[1m[0mlimit[0m[0m     = 1024
              [32m+[0m [0m[1m[0mreserved[0m[0m  = (known after apply)
              [32m+[0m [0m[1m[0mused[0m[0m      = (known after apply)
            }

          [32m+[0m [0mmemory {
              [32m+[0m [0m[1m[0mallocated[0m[0m = 1024
              [32m+[0m [0m[1m[0mlimit[0m[0m     = 1024
              [32m+[0m [0m[1m[0mreserved[0m[0m  = (known after apply)
              [32m+[0m [0m[1m[0mused[0m[0m      = (known after apply)
            }
        }

      [32m+[0m [0mstorage_profile {
          [32m+[0m [0m[1m[0mdefault[0m[0m            = true
          [32m+[0m [0m[1m[0menabled[0m[0m            = true
          [32m+[0m [0m[1m[0mlimit[0m[0m              = 10240
          [32m+[0m [0m[1m[0mname[0m[0m               = "*"
          [32m+[0m [0m[1m[0mstorage_used_in_mb[0m[0m = (known after apply)
        }
    }

[0m[1mPlan:[0m 5 to add, 0 to change, 0 to destroy.
[0m[0m[1m
Do you want to perform these actions?[0m
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  [1mEnter a value:[0m [0myes

[0m[1mvcd_org.org: Creating...[0m[0m
[0m[1mvcd_org_user.: Creating...[0m[0m
[0m[1mvcd_network_routed.-Internal-Network: Creating...[0m[0m
[0m[1mvcd_org_vdc.-VDC: Creating...[0m[0m
[0m[1mvcd_edgegateway.-ESG: Creating...[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1m[org creation] error creating Org : error instantiating a new Org: 401 Unauthorized[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with vcd_org.-org,
[31m│[0m [0m  on terraform-vcloud.tf line 30, in resource "vcd_org" "-org":
[31m│[0m [0m  30: resource "vcd_org" "-org"[4m{[0m[0m
[31m│[0m [0m
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1m[resourceToUserData] [ENF] entity not found[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with vcd_org_user.,
[31m│[0m [0m  on terraform-vcloud.tf line 82, in resource "vcd_org_user" "":
[31m│[0m [0m  82: resource "vcd_org_user" "" [4m{[0m[0m
[31m│[0m [0m
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mRequest cancelled[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with vcd_org_vdc.-VDC,
[31m│[0m [0m  on terraform-vcloud.tf line 98, in resource "vcd_org_vdc" "-VDC":
[31m│[0m [0m  98: resource "vcd_org_vdc" "-VDC" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mThe plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mRequest cancelled[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with vcd_edgegateway.-ESG,
[31m│[0m [0m  on terraform-vcloud.tf line 132, in resource "vcd_edgegateway" "-ESG":
[31m│[0m [0m 132: resource "vcd_edgegateway" "-ESG" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mThe plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
[31m╵[0m[0m
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mPlugin did not respond[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with vcd_network_routed.-Internal-Network,
[31m│[0m [0m  on terraform-vcloud.tf line 182, in resource "vcd_network_routed" "-Internal-Network":
[31m│[0m [0m 182: resource "vcd_network_routed" "-Internal-Network" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mThe plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more detail
s.
[31m╵[0m[0m

Stack trace from the terraform-provider-vcd_v3.3.1.exe plugin:

panic: edge gateway '-ESG' not found: error retrieving Org and VDC: error retrieving Org : [ENF] entity not found

goroutine 115 [running]:
github.com/vmware/terraform-provider-vcd/v3/vcd.(*VCDClient).lockParentEdgeGtw(0xc0005f3630, 0xc000394900)
        github.com/vmware/terraform-provider-vcd/v3/vcd/config.go:272 +0x445
github.com/vmware/terraform-provider-vcd/v3/vcd.resourceVcdNetworkRoutedCreate(0xc000394900, 0xeb9d80, 0xc0005f3630, 0x0, 0x0)
        github.com/vmware/terraform-provider-vcd/v3/vcd/resource_vcd_network_routed.go:184 +0x9a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0002f6600, 0x10089c8, 0xc0002ea2c0, 0xc000394900, 0xeb9d80, 0xc0005f3630, 0x0, 0x0,
0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:278 +0x95
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002f6600, 0x10089c8, 0xc0002ea2c0, 0xc00029cee0, 0xc0003a6720, 0xeb9d80, 0xc0005f3630, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/resource.go:396 +0x674
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002f0750, 0x10089c8, 0xc0002ea2c0, 0xc0005f20a0, 0xc0002ea2c0, 0xe7f9a0, 0xc000378100)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.4.4/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0003a6420, 0x1008a70, 0xc0002ea2c0, 0xc00029cd90, 0xc0003a6420, 0xc0003781b0, 0xc000661ba0)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:332 +0xb6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xe7f9a0, 0xc0003a6420, 0x1008a70, 0xc0003781b0, 0xc00006a300, 0x0, 0x1008a70, 0xc0003781b0, 0xc000512000, 0x28f)
        github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d0c40, 0x1012938, 0xc000420480, 0xc00026c300, 0xc000040450, 0x14c2700, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001d0c40, 0x1012938, 0xc000420480, 0xc00026c300, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00028c1e0, 0xc0001d0c40, 0x1012938, 0xc000420480, 0xc00026c300)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-vcd_v3.3.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by edwardmedia** [comment]
@Reham-Fahmy what led you think this is a bug of the [Terraform Provider Google?](https://github.com/hashicorp/terraform-provider-google). Without seeing the config, it is hard to be certain. But with the limited log, it seems this is not the right place. I am afraid we can not help you.

**Comment by Reham-Fahmy** [comment]
> @Reham-Fahmy what led you think this is a bug of the [Terraform Provider Google?](https://github.com/hashicorp/terraform-provider-google). Without seeing the config, it is hard to be certain. But with the limited log, it seems this is not the right place. I am afraid we can not help you.


For Terraform Provider Google label,it's added automatically and i cannot update it.where the right provider is vmware vcloud director.after removing the credentials and public ips ,i attach the configuration files to be reviwed in the below link,

https://github.com/Reham-Fahmy/Terraform-with-vcd

**Comment by Reham-Fahmy** [comment]
8

**Comment by edwardmedia** [comment]
@Reham-Fahmy below is what I see from your attached files. I wish I could help you but I guess you may need to contact the owner of that provider for help. Clearly there is not much we can do right now. Feel free to reopen if you see an issue with the TPG.  

```tf
# Configure the VMware vCloud Director Provider - Start
terraform {
  
  required_providers {
    vcd = {
      source = "vmware/vcd"
      version = "3.3.1"
    }
  }
}
```
